### ISSUE TITLE
Split rules for Survival Analysis, and speed

### ISSUE THREAD

**Issue by YohannLeFaou** [kogalur/randomForestSRC#1]
Dear Professor,

I'm a PhD student in Actuarial Sciences and I'm working on the topic of Survival Analysis. Currently I'm studying a  Random Forest method which aims to model E[phi(T)|X] where :

- T is a censored time random variable
- X is a vector of covariates
- phi is a given real function

I'm using RSF algorithm from randomForestSRC package as a benchmark to my method. There is a presentation [here](https://github.com/YohannLeFaou/YohannLeFaou.github.io/blob/master/Slides___Random_Forest_for_regression_of_a_censored_variable.pdf) if you are curious.

I have a small problem since I need to do repeated experiments on large datasets (from 10000 to 100000 observations). I found the rfsrc function is a bit slow to handle such data. I followed different advices you give in the function documentation to reduce the computation time : 

- setting nsplit to small value
- setting nodesize to higher value
- manually specifying the "ntime" parameter
- etc..

In fact my question is about the split rules you mention in the articles "Random Survival Forest (2008)" and the R vignette "Random Survival Forests for R (2007)".

In "Random Survival Forests for R (2007)", you talk about different splitrules :

- logrank
- logrank score splitting
- approximate logrank score splitting
- Conservation of events splitting (May it apply with right censored data ?)

In "Random Survival Forest (2008)", in the "Empirical Comparisons" paragraph, you mention :

- logrank
- logrank score
- logrank random
- Conservation of event splitting

So "approximate logrank" is replaced by "logrank random". My question is : Do you confirm that the splitrule "approximate logrank" is not featured in the today randomForestSRC package ?

Finally, I would like to thank you for the very great RSF algorithm !

Best,
Yohann le Faou

**Comment by kogalur** [comment]
You are correct.  There are two split rules for survival:  logrank and logrank score.  When combined with the option nsplit > 0, a maximum of nsplit points are randomly chosen among the possible split points for the x-variable being considered. This can significantly reduce the computation time when compared to deterministic splitting (nsplit=0).  Reducing the time points of interest via ntime will also help.  Finally, you should also ensure that you are running an OpenMP version of the package to take full advantage of your hardware.  We expect to have the next version posted here and on CRAN in a day or two, so please upgrade at that point.  Thank you.

ubk

**Comment by YohannLeFaou** [comment]
Thanks for your answer.
