### ISSUE TITLE
Test data requires y column for prediction

### ISSUE THREAD

**Issue by saosebastiao** [kogalur/randomForestSRC#10]
I have a problem where I'm trying to predict 15 minutes into the future. I've set up my model and have good results, but when I try to apply the model to current data where my y-vals are still unknown, the predict(model,test) won't give me any output for those rows. 

I've tried:
1) Not supplying the yvar data in the data.frame for `predict()`. This silently errors, predicting 0 for all rows. 

2) Using `na.action = "na.impute". This gives me correct output, but spends a significant amount of time (6x longer than predict with "na.omit" in my case). Since there are no NAs in my xvars, I'm assuming it is imputing values for irrelevant data, such as unused variables in my data.frame or yvars. 

3) Supplying yvars as part of a separate data.frame (ex. `rfsrc(yvars$yval ~ xvar1 + xvar2, data=train)`). This fails with `Error in parseFormula(formula, data, ytry) : 
  formula is incorrectly specified.`

Is there any way that I can supply y vars separately, such that they aren't needed for the prediction phase?

**Comment by kogalur** [comment]
Please supply us with a minimal code example with which we can reproduce and investigate your issue.

**Comment by gse-cc-git** [comment]
Hi @saosebastiao have you found a solution to your issue ? I might be facing something similar with a classification model where the output of pred$predicted is giving 0 for all cases, although it's working as expected with the `data(breast)` example of the package.

**Comment by kogalur** [comment]
Please supply us with a minimal code example with which we can reproduce and investigate your issue.  It's difficult to even begin to address your issue without it.

**Comment by gse-cc-git** [comment]
@saosebastiao sorry to "hijack" your thread :
@kogalur  below is a MRE

```
data(breast, package = "randomForestSRC")
breast.obj <- rfsrc(status ~ ., data = breast[(1:100), ], nsplit = 10)

# prediction call removing the y column (status)
breast.pred <- predict(breast.obj, breast[-(1:100),-1 ])
print(head(breast.pred$predicted))
print(breast.pred$class)
```

Prediction probability: 0 for all rows
```
> print(head(breast.pred$predicted))
     N R
[1,] 0 0
[2,] 0 0
[3,] 0 0
[4,] 0 0
[5,] 0 0
[6,] 0 0
```

Predicted class: ~equiprobability:
```
> table(breast.pred$class)

 N  R 
48 49 
```

To be compared with the package's code example: note the univocal prediction of the N modality
```
> data(breast, package = "randomForestSRC")
> breast.obj <- rfsrc(status ~ ., data = breast[(1:100), ], nsplit = 10)
> breast.pred <- predict(breast.obj, breast[-(1:100),])
> print(head(breast.pred$predicted))
         N     R
[1,] 0.862 0.138
[2,] 0.740 0.260
[3,] 0.896 0.104
[4,] 0.646 0.354
[5,] 0.881 0.119
[6,] 0.626 0.374
> print(breast.pred$class)
 [1] N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N N
[72] N N N N N N N N N N N N N N N N N N N N N N N N N N
Levels: N R
```

A mis-understanding of mine of how to cod ea classification run ?

**Comment by saosebastiao** [comment]
Thanks @gse-cc-git , that's exactly the problem I had, I've just been away from my computer for a couple days. 

Personally, it's not that big of a deal, as you can easily solve it with `data[is.na(data]<-0` or similar. It's just a break from how most modeling and prediction functions work in the world of R, and it took me a while to figure out what was going on.

**Comment by gse-cc-git** [comment]
Hi @kogalur. You welcome. Thank you very much for sharing your work. I'd like to know more of mathematics to be able to contribute more significantly but unfortunately...

**Comment by kogalur** [comment]
This repository has been updated to release 2.6.1 with the fix.  CRAN should be live with the fix momentarily.  Thanks!
