### ISSUE TITLE
Error in pv$cores %??% 1L : could not find function "%??%"

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [kogalur/randomForestSRC#104]
Hi!

I am running the classif.rfsrc in mlr3, which is the randomForestSRC, adapted for mlr3. I get this error:
Error in pv$cores %??% 1L : could not find function "%??%"

My research shows that this could relate to the parallel- package which may be used inside rfsrc. So I reinstalled that and later reinstalled R and all packages from scratch, but the error persists. 

Any ideas?
Thank You und Dankeschön!

**Comment by kogalur** [comment]
You need to provide us with simple script that will allow us to duplicate this issue.  It needs to be a script that loads our package directly, and does not deploy our package as a reverse depends.  Thank you.
