### ISSUE TITLE
How to get the input data with imputed data overlaid of `predict.rfsrc`

### ISSUE THREAD

**Issue by sinowitabc** [kogalur/randomForestSRC#105]
Hi, I tried to overlay the missing values in input data with `(rfsrc, predict)` object's `imputed.data` values, but I got a different error rate when predicted on that dataset. So what's the actual data the model predicted on?
```
library(randomForestSRC)
set.seed(123)
data(pbc, package = "randomForestSRC")
f <- as.formula(Surv(days, status) ~ .)
rsf_obj <- rfsrc(f, pbc, na.action="na.impute")
rsf_pred <- predict(rsf_obj, pbc, na.action = "na.impute") # error rate: 11.83020898%
tmp <- as.data.frame(cbind(rsf_pred$yvar, rsf_pred$xvar))
tmp[rsf_pred$imputed.indv, names(rsf_pred$imputed.data)] <- rsf_pred$imputed.data
predict(rsf_obj, tmp) # error rate: 12.95406166%
```
BTW, in the docs of `impute.rfsrc`, it says
>  if the user imputes data with `nimpute=2` and runs a grow forest using this imputed data, then performance values such as VIMP and error rates will coincide with those obtained by running a grow forest on the original non-imputed data using
`na.action = "na.impute"`

I tried to impute the input data beforehand using `impute.rfsrc` with default arguments, but I can't get coincident performance (and it differs from above). Are there any examples for reference?

Sincerely

**Comment by ishwaran** [comment]
Let's forget for the moment about missing data.

The call

`rsf_pred <- predict(rsf_obj, pbc)`

Is running the training data down a forest trained on the same data.  So this will be optimistically biased and not useful.  The `predict` call is meant for running new test data.  And if no data is passed to `predict`, then it will restore the forest.  I recommend you carefully consult the help file to make sure you understand what is happening here.

**Comment by ishwaran** [comment]
Regarding the help file for `impute.rfsrc` we agree the way it is written is confusing.  We will edit this and update the help file in the next CRAN build. Thank you.

**Comment by sinowitabc** [comment]
> Let's forget for the moment about missing data.
> 
> The call
> 
> `rsf_pred <- predict(rsf_obj, pbc)`
> 
> Is running the training data down a forest trained on the same data. So this will be optimistically biased and not useful. The `predict` call is meant for running new test data. And if no data is passed to `predict`, then it will restore the forest. I recommend you carefully consult the help file to make sure you understand what is happening here.

😄 Thank you for your reply. I think I made the code confusing (here I want to get the error rate on the full dataset rather than on the OOB data). To make it clear, I split the dataset and the error rates keep different.
```
data(pbc, package = "randomForestSRC")
f <- as.formula(Surv(days, status) ~ .)
set.seed(123)
train <- sample(seq_len(nrow(pbc)), round(nrow(pbc) * 0.80))
rsf_obj <- rfsrc(f, pbc[train,], na.action="na.impute")
rsf_pred <- predict(rsf_obj, pbc[-train,], na.action = "na.impute")
rsf_pred # error rate: 20.43172691%
tmp <- as.data.frame(cbind(rsf_pred$yvar, rsf_pred$xvar))
tmp[rsf_pred$imputed.indv, names(rsf_pred$imputed.data)] <- rsf_pred$imputed.data
predict(rsf_obj, tmp) # error rate: 21.98795181%
```
