### ISSUE TITLE
Prediction Behavior on NA

### ISSUE THREAD

**Issue by mro-dbolta** [kogalur/randomForestSRC#107]
Many thanks for the great package!
Is there a way for predict.rfsrc to return NA values for rows which fail to generate predictions?

Current behavior is predict.rfsrc returns shortened vector of predictions.
Eg. for my specific mutivariate regression use case (if bad data exists):
predictions <- predict(rfsrc_model, newdata = df)$regrOutput$y1$predicted
length(predictions) < nrow(df)

I can use a workaround with predict(..., na.action = "na.impute")
And use a comparison between the two resulting prediction vectors to find which new values are from imputation.

**Comment by ishwaran** [comment]
Missing data will be removed by default.  From rfsrc help file:

```
na.action: Action taken if the data contains ‘NA’'s.  Possible values
          are ‘na.omit’ or ‘na.impute’.  The default ‘na.omit’ removes
          the entire record if even one of its entries is ‘NA’ (for
          x-variables this applies only to those specifically listed in
          'formula').  Selecting ‘na.impute’ imputes the data.  Also
          see the function ‘impute’ for fast direct imputation.
```

Therefore if there is missing data along a row, that data is removed and you cannot get prediction for that row.

Maybe you can do the following:

```
which.na <- is.na(data)
r.na <- rowSums(which.na) > 0
names(r.na) <- rownames(data)
```

This records which of your rows will be removed in the analysis and allow you to determine which predicted values returned from the analysis are for the complete (non-missing) data.

For extra safety, I give the vector r.na the same rownames as your data frame.
