### ISSUE TITLE
OOB error rate plot broken with version 2.6.0

### ISSUE THREAD

**Issue by rkmsxi** [kogalur/randomForestSRC#11]
## Issue

It seems that the error rate plot method was broken in release 2.6

```{r}
library(randomForestSRC, verbose = TRUE)
```

>  randomForestSRC 2.6.1 
>  
>  Type rfsrc.news() to see new features, changes, and bug fixes. 
> 

Using the example from the help file you can see that the plot is outputting a constant error rate like when the `tree.err` option is set to `FALSE`:
```{r }
## veteran data
## randomized trial of two treatment regimens for lung cancer
data(veteran, package = "randomForestSRC")
v.obj <- rfsrc(Surv(time, status) ~ ., data = veteran, ntree = 100, tree.err=TRUE)

plot(v.obj)
```
![image](https://user-images.githubusercontent.com/39488382/40311016-898a6e1c-5d06-11e8-8e66-d206cbd6cd07.png)

You get the same plot with explicitly setting tree.err = FALSE:
```{r }
v.obj <- rfsrc(Surv(time, status) ~ ., data = veteran, ntree = 100, tree.err = FALSE)

plot(v.obj)
```
![image](https://user-images.githubusercontent.com/39488382/40311056-a544c3dc-5d06-11e8-9b03-35e2fbf651b6.png)

The variable importance plot is still working:
```{r }
v.obj <- rfsrc(Surv(time, status) ~ ., data = veteran, ntree = 100, tree.err = TRUE,
                     importance = TRUE)

plot(v.obj)
```
![image](https://user-images.githubusercontent.com/39488382/40311105-cb1f8e16-5d06-11e8-8502-97108b8a719a.png)

Version 2.5.1 was working fine. I remove version 2.6.1, install 2.5.1, and get the correct OOB error rate plot.
```{r results="hide"}
remove.packages("randomForestSRC", lib="~/R/win-library/3.5")
install.packages("C:/Users/*******/Downloads/randomForestSRC_2.5.1.tar.gz", repos = NULL, type = "source")
```
```{r}
library(randomForestSRC, verbose = TRUE)
```

>  randomForestSRC 2.5.1 
>  
>  Type rfsrc.news() to see new features, changes, and bug fixes. 
> 

```{r }
data(veteran, package = "randomForestSRC")
v.obj <- rfsrc(Surv(time, status) ~ ., data = veteran, ntree = 100, tree.err = TRUE)
plot(v.obj)
```
![image](https://user-images.githubusercontent.com/39488382/40311127-df9228e0-5d06-11e8-9f75-3178ab14e007.png)

Session Info for reference:
```{r }
sessionInfo()
```

> R version 3.5.0 (2018-04-23)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] randomForestSRC_2.5.1
> 
> loaded via a namespace (and not attached):
>  [1] compiler_3.5.0  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2 parallel_3.5.0  htmltools_0.3.6 tools_3.5.0    
>  [8] yaml_2.1.19     Rcpp_0.12.17    stringi_1.2.2   rmarkdown_1.9   knitr_1.20      stringr_1.3.1   digest_0.6.15  
> [15] evaluate_0.10.1

Any help would be appreciated, thanks!

**Comment by kogalur** [comment]
The option err.rate has been superseded with the new more informative option err.block.  Please see the documentation.  Thanks.

**Comment by rkmsxi** [comment]
That's understandable and thanks, but I suggest updating your examples on the `rfsrc` help page. It still has `tree.err=TRUE` throughout in lieu of `err.block=TRUE`. For example:

> Examples
> 
> \##------------------------------------------------------------
> \## Survival analysis
> \##------------------------------------------------------------
> 
> 
> \## veteran data
> \## randomized trial of two treatment regimens for lung cancer
> data(veteran, package = "randomForestSRC")
> v.obj <- rfsrc(Surv(time, status) ~ ., data = veteran, ntree = 100, tree.err=TRUE)
> 
> \# print and plot the grow object
> print(v.obj)
> plot(v.obj)

Cheers for the speedy response!

**Comment by kogalur** [comment]
Right!  Thanks!
