### ISSUE TITLE
Negative Error Rate in Competing Risk Setting

### ISSUE THREAD

**Issue by jatherrien** [kogalur/randomForestSRC#15]
Hello, I ran a model on a large competing risk dataset (250,000 observations and 74 covariates). I wasn't able to run using more observations without running into errors about allocating vectors of length greater than 32-bit, but for 250,000 rows it ran without complaint. I only mention this as it may be related.

Anyway, my output from `print.rfsrc(model)` is:
```
                         Sample size: 250000
                    Number of events: 102523, 22320
                    Was data imputed: yes
                     Number of trees: 10000
           Forest terminal node size: 6
       Average no. of terminal nodes: 1888.076
No. of variables tried at each split: 9
              Total no. of variables: 74
                            Analysis: RSF
                              Family: surv-CR
                      Splitting rule: logrankCR *random*
       Number of random split points: 3
                          Error rate: -15.41%, 34.04%
```
The error rate for the first event is *negative* 15.41%, which if I understood how the error rate is calculated with the concordance index isn't possible. 

Here is the call I made: `model = rfsrc(formula = Surv(u, delta) ~ . - sub_grade, data = data, ntree = 10000, nsplit = 3, importance = "none", na.action = "na.impute", ntime = 0:37, cause = 1, proximity = FALSE, sampsize = 10000, forest.wt = FALSE)`

Here is the `sessionInfo()` on the machine that trained the model:
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] survival_2.41-3       randomForestSRC_2.6.1

loaded via a namespace (and not attached):
[1] compiler_3.4.4  Matrix_1.2-12   parallel_3.4.4  splines_3.4.4  
[5] grid_3.4.4      lattice_0.20-35
```

For reference I earlier ran the same call on a smaller subset of 100,000 rows which gave error rates of 42.63%, 34.17%.

**Comment by kogalur** [comment]
Passing long vectors (> 32-bits in length) from C -> R is on our list of campaigns, and will be in a future build.   There are, unfortunately, other limitations in the code related to integer values > 32-bits.  One of these is the C-index calculation.  The number of pairs in the denominator of the calculation is n x (n-1) / 2.  Unfortunately, with n=250,000, this is wraps around through zero reducing the value to modulo UINT_MAX.  Thus, when the fraction is greater than 1, 1 - fraction is less than 0.  These issues will be addressed in a future build, but for now, you will have to reduce dimensionality.  Also, you can further reduce dimensionality by allowing ntree to assume the default value of 1000.  It's likely that you only need several hundred trees and not even 1000.  10,000 is most certainly excessive.

**Comment by jatherrien** [comment]
Alright, thank you for the advice and the quick response.
