### ISSUE TITLE
Class imbalance: is thresholding implemented yet ?

### ISSUE THREAD

**Issue by gse-cc-git** [kogalur/randomForestSRC#16]
I read on [SO that its in your plans](https://stackoverflow.com/questions/47128865/randomforestsrc-sampling-scheme).
Is it adequate for imbalance in multiclass classification problems ?

Thanks.

**Comment by kogalur** [comment]
We will be including imbalanced analysis for classification the next CRAN build if things go as planned.  We're still a few weeks away from that.

**Comment by kogalur** [comment]
Imbalanced analysis is now available in 2.8.0.
