### ISSUE TITLE
Maximal Subtrees Not Detecting Noisy Variables

### ISSUE THREAD

**Issue by jatherrien** [kogalur/randomForestSRC#17]
I'm working with a dataset with around 70 variables in the competing risk setting (same dataset as in my last issue, although I've reduced my rows to 100,000). Some of these variables I expect are more noisy while others are stronger, so I ran the `max.subtree` function to look at the top variables. However, the threshold returned is extremely high (about 22) while the highest order is only 11. Suspicious of these results I created a fake, random covariate entirely unrelated to the response and introduced that into the model, and it received an order of about 6 (threshold being 22).

Thinking that this may be unique to my dataset/random chance I tried the survival example in the max.subtree documentation (veteran dataset). In that example I introduced 10 extra random covariates and they all were included in the top variables (not all of the original variables made it when I added extra variables which differs from my dataset, although they all were considered strong when I included no extra variables) I've run it several times with the same results so I know it's not that the random covariates are somehow by random chance related to the response.

I don't know enough about maximal subtrees and its assumptions to know whether this is a problem in my dataset or not, but being able to reproduce it in the example dataset was surprising. Any insight would be appreciated.

Here is some R code for what I did in the example.
```
require(randomForestSRC)

data(veteran, package = "randomForestSRC")

for(j in 1:10){
  veteran[,paste0("random", j)] = rnorm(nrow(veteran))
}

v.obj <- rfsrc(Surv(time, status) ~ . , data = veteran)
v.max <- max.subtree(v.obj)

v.max$order
v.max$threshold
v.max$topvars
```

Here is my `sessionInfo()`
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] randomForestSRC_2.6.1

loaded via a namespace (and not attached):
[1] compiler_3.4.4 parallel_3.4.4 tools_3.4.4
 ```

**Comment by kogalur** [comment]
Thank you for this information and the minimal example.  We're going to look into this and get back to you shortly.  As a work-around, we suggest that you use importance=TRUE for variable importance measures, and avoid using max.subtree() for the time being.

**Comment by ishwaran** [comment]
With increasing dimension, you also need to increase mtry otherwise tree splitting will be predominately guided by noise variables.  Therefore artificially improving their maximal depth.  I would even try mtry=p where p is the number of variables-in other words use bagging.  Remember that variable selection is different than prediction.
