### ISSUE TITLE
Complete crash on presence of NaN in covariate

### ISSUE THREAD

**Issue by jatherrien** [kogalur/randomForestSRC#18]
Hello, I was working in a dataset that happened to have some NaN s (distinct from NAs) in one of the columns and upon running `rfsrc` many ugly error messages appeared that led to R completely crashing. I've included some example code below that replicates the problem.

I'm unsure how I would expect the package to treat NaN's as they can be distinct from NAs in certain problems (mine included); but informative error messages that identify the presence of NaN's causing problems would be helpful, or perhaps a precheck that forces users to handle NaN's themselves.

Here's example code that triggers the problem - I suggest running it in base R as Rstudio doesn't always display all of the errors.
```
x = rnorm(100)
z = x + rnorm(100)

y = 5 + 2*x - z + rnorm(100)

d = data.frame(x,z,y)

require(randomForestSRC)

rfsrc(y~x+z, d, na.action="na.impute", ntree=500) # so far so good - no issue

d$z[1:10] = NA

rfsrc(y~x+z, d, na.action="na.impute", ntree=500) # Still works fine, though we impute

d$z[1] = NaN
rfsrc(y~x+z, d, na.action="na.impute", ntree=500) # massive failure
```

**Comment by jatherrien** [comment]
I forgot to post my `sessionInfo()`:
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] randomForestSRC_2.6.1

loaded via a namespace (and not attached):
[1] compiler_3.4.4 parallel_3.4.4

```

**Comment by kogalur** [comment]
Thank you for informing us about this issue.  We'll include a fix in the next build.  Our solution will be to pre-process the data and replace NaN's with NA's.  In the meantime, you'll have to pre-process the data yourself before feeding it to the package.

**Comment by kogalur** [comment]
This has been fixed in the latest build.  Thanks.
