### ISSUE TITLE
I think the subset argument in the plot.variable function is not working.

### ISSUE THREAD

**Issue by amoljpande** [kogalur/randomForestSRC#2]
Please find the attached R script as an example which shows that the subset argument in the plot.variable function doesn't seem to be working. 

[BugVariablePlot.txt](https://github.com/kogalur/randomForestSRC/files/1459668/BugVariablePlot.txt)

**Comment by kogalur** [comment]
This was indeed a bug on the R-side. We were not allowing subsetting in the partial mode call.  We have removed this restriction and will include the fix in the next beta build.
