### ISSUE TITLE
Error rate is constant, independent of the number of trees

### ISSUE THREAD

**Issue by jasiozaucha** [kogalur/randomForestSRC#20]
Both in the example provided:
`# Veteran's Administration Lung Cancer Trial. Randomized 
# trial of two treatment regimens for lung cancer.
data(veteran, package = "randomForestSRC")
v.obj <- rfsrc(Surv(time, status) ~ ., data = veteran, ntree = 100)
## Plot the error.
plot(v.obj)
## Plot the survival estimates.
plot.survival(v.obj)`
and with my own data the error rate is constant (horizontal line), independent of the number of trees. Is this normal i.e. the expected behaviour?

**Comment by kogalur** [comment]
Please look at the block.size parameter in the latest version of the package.  This will allow you to have and plot the error rate at every tree.
