### ISSUE TITLE
Dont-test issue on CRAN

### ISSUE THREAD

**Issue by tsrobinson** [kogalur/randomForestSRC#202]
Hi there, I'm a huge fan of randomForestSRC and use it in a separate R package (cjbart). I got an email to say that it was going to be archived because of a dont-test issue.

I tried to replicate the error from the out file, but on macOS 12.1 and Ubuntu 20.04 (both on R4.1.2) the code runs perfectly, so I suspect this is just a niche compatibility issue with the test server.

Would you be able to alter the wrapper for the affected code to \dontrun{} so we don't lose this important piece of software? 

If you already have a fix, please just close this issue and thanks again for the great software!

**Comment by ishwaran** [comment]
Hi, thanks.  We've already submitted the update. It's in review. We should be at 3.0.1 shortly.  Thanks!

**Comment by tsrobinson** [comment]
Thanks @ishwaran -- really appreciate it!
