### ISSUE TITLE
Error when trying to predict using version 2.7.0

### ISSUE THREAD

**Issue by husamrahman** [kogalur/randomForestSRC#21]
I obtain the following error when trying to predict an rfsrc object: 

"<simpleError in (object$nativeFactorArray)$mwcpPT: $ operator is invalid for atomic vectors>
Error in generic.predict.rfsrc(object, newdata, ensemble = ensemble, m.target = m.target,  : 
  An error has occurred in prediction.  Please turn trace on for further analysis.

This is the first time I see this error in months as I am just loading the same RDS model object and generating predictions on new data. I even tried just predicting on the model data that was used to build the model and I get the same error.

The model was built using package Version: 2.5.1.
I only started to see this error once I installed the latest randomForestSRC package: Version 2.7.0.
To confirm, i reverted back to Version 2.5.1. and predict started to work again.

**Comment by kogalur** [comment]
We might have broken the ability to restore models grown with previous builds.  In theory, we should backwards compatible with 2.3.0, but we'll look into it.  In the mean time, you might want to regrow your forest with the latest build.

**Comment by kogalur** [comment]
If you are able to give a minimal data set and script that, even randomly, reproduces this, it would be very helpful.  Also, session information, OS, and the like would be appreciated.

**Comment by shadogray** [comment]
sorry for this bad formatting by my webmail 
below my sessinfo
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-suse-linux-gnu (64-bit)
Running under: openSUSE Tumbleweed

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] FactoMineR_1.41   ggcorrplot_0.1.2  mlr_2.13          ParamHelpers_1.11 forcats_0.3.0     stringr_1.3.1    
 [7] dplyr_0.7.8       purrr_0.2.5       readr_1.2.1       tidyr_0.8.2       tibble_1.4.2      ggplot2_3.1.0    
[13] tidyverse_1.2.1   assertthat_0.2.0 

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5     splines_3.5.1        haven_2.0.0          lattice_0.20-38      colorspace_1.3-2    
 [6] yaml_2.2.0           survival_2.43-3      rlang_0.3.0.1        pillar_1.3.0         glue_1.3.0          
[11] withr_2.1.2          modelr_0.1.2         readxl_1.1.0         bindrcpp_0.2.2       bindr_0.1.1         
[16] plyr_1.8.4           munsell_0.5.0        gtable_0.2.0         cellranger_1.1.0     rvest_0.3.2         
[21] leaps_3.0            knitr_1.20           parallelMap_1.3      parallel_3.5.1       broom_0.5.0         
[26] Rcpp_1.0.0           flashClust_1.01-2    scales_1.0.0         backports_1.1.2      checkmate_1.8.5     
[31] scatterplot3d_0.3-41 jsonlite_1.5         fastmatch_1.1-0      hms_0.4.2            stringi_1.2.4       
[36] BBmisc_1.11          grid_3.5.1           cli_1.0.1            tools_3.5.1          magrittr_1.5        
[41] lazyeval_0.2.1       cluster_2.0.7-1      crayon_1.3.4         pkgconfig_2.0.2      MASS_7.3-51.1       
[46] Matrix_1.2-14        data.table_1.11.8    xml2_1.2.0           lubridate_1.7.4      httr_1.3.1          
[51] rstudioapi_0.8       R6_2.3.0             nlme_3.1-137         compiler_3.5.1

**Comment by shadogray** [comment]
meanwhile I learned to debug, this is now compiled from github code:

* thread #1, name = 'R', stop reason = signal SIGSEGV: invalid address (fault address: 0xf3ece470)
    frame #0: 0x00007fffe219029f randomForestSRC.so`stackAndConstructSplitVector(treeID=32767, repMembrSize=4152980969, randomCovariateIndex=1, splitVector=0x0000000061a34b48, splitVectorSize=115677, factorFlag="", deterministicSplitFlag="", mwcpSizeAbsolute=0x00007ffffffaa7a0, splitVectorPtr=0x000000000285c718) at randomForestSRC.c:14130
   14127            }
   14128          }  
   14129          else {
-> 14130            *factorFlag = FALSE;
   14131            if (RF_splitRule == RAND_SPLIT) {
   14132              splitLength = 1 + 1;
   14133              *deterministicSplitFlag = FALSE;


(lldb) bt
* thread #1, name = 'R', stop reason = signal SIGSEGV: invalid address (fault address: 0xf3ece470)
  * frame #0: 0x00007fffe219029f randomForestSRC.so`stackAndConstructSplitVector(treeID=32767, repMembrSize=4152980969, randomCovariateIndex=1, splitVector=0x0000000061a34b48, splitVectorSize=115677, factorFlag="", deterministicSplitFlag="", mwcpSizeAbsolute=0x00007ffffffaa7a0, splitVectorPtr=0x000000000285c718) at randomForestSRC.c:14130
    frame #1: 0x00007fffe219140b randomForestSRC.so`classificationXwghtSplit(treeID=32767, parent=0x00007ffff7dd6128, repMembrIndx=0x000000006197bcf4, repMembrSize=4152980969, allMembrIndx=<unavailable>, allMembrSize=<unavailable>, splitParameterMax=0x00007ffffffa9190, splitValueMaxCont=0x00007ffffffa9198, splitValueMaxFactSize=0x00007ffffffa9194, splitValueMaxFactPtr=0x00007ffffffa91a0, splitStatistic=0x00000001fffa91a8, splitIndicator=0x00007ffffffa91b0, splitMIA="", multImpFlag='\0') at randomForestSRC.c:8455
    frame #2: 0x00007fffe21a9dbe randomForestSRC.so`growTree(r=1, rootFlag=<unavailable>, multImpFlag=<unavailable>, treeID=49, parent=0x000000001474b230, repMembrIndx=<unavailable>, repMembrSize=0, allMembrIndx=0x000000006146d944, allMembrSize=189328, bootMembrIndxIter=0x00007ffffffa92a4, rmbrIterator=0x00007ffffffa92a8, ambrIterator=0x00007ffffffa92ac) at randomForestSRC.c:20892
    frame #3: 0x00007fffe21b4794 randomForestSRC.so`acquireTree(mode=<unavailable>, r=1, b=49) at randomForestSRC.c:20027
    frame #4: 0x00007fffe21b50d0 randomForestSRC.so`rfsrc._omp_fn.0((null)=<unavailable>) at randomForestSRC.c:6575
    frame #5: 0x00007ffff730ee9f libgomp.so.1`GOMP_parallel + 63
    frame #6: 0x00007fffe21b1363 randomForestSRC.so`rfsrc(mode='\x01', seedValue=<unavailable>) at randomForestSRC.c:6572
    frame #7: 0x00007fffe21b324b randomForestSRC.so`rfsrcGrow(traceFlag=<unavailable>, seedPtr=<unavailable>, optLow=<unavailable>, optHigh=<unavailable>, splitRule=<unavailable>, nsplit=<unavailable>, mtry=0x00000000424a7440, htry=0x00000000424a7478, ytry=0x00000000424a7670, nodeSize=0x00000000424a76a8, nodeDepth=0x00000000424a7750, crWeightSize=0x00000000424a7788, crWeight=0x000000001cb2a948, ntree=0x00000000424a7830, observationSize=0x00000000424b2940, ySize=0x00000000424a7948, rType=0x00000000424d2330, rLevels=0x00000000424a7980, rData=0x000000005b3ad5a0, xSize=0x00000000424aeb48, xType=0x000000001ec0aec0, xLevels=0x000000002d0b68d8, bootstrapSize=0x00000000424af168, bootstrap=0x000000001cb2b240, caseWeight=0x000000005b51f260, xSplitStatWeight=0x000000000ebee360, yWeight=0x00000000424afa98, xWeight=0x0000000019487970, xData=0x00007ffe19d3c010, timeInterestSize=0x000000000285d160, timeInterest=0x00007ffff7c92d10, nImpute=0x000000001cb21cc0, perfBlock=0x000000000000005d, numThreads=0x0000000000000001) at randomForestSRC.c:21480
    frame #8: 0x00007ffff7850c1e libR.so`R_doDotCall(ofun=<unavailable>, nargs=<unavailable>, cargs=<unavailable>, call=<unavailable>) at dotcode.c:791
    frame #9: 0x00007ffff78517f6 libR.so`do_dotcall(call=0x0000000007d090b0, op=<unavailable>, args=<unavailable>, env=<unavailable>) at dotcode.c:1252
    frame #10: 0x00007ffff792652b libR.so`InInteger(stream=<unavailable>) at serialize.c:424

**Comment by shadogray** [comment]
I must apologize, finally I did a memory test, after 3 years my workhorse shows memory defects.
Please ignore abovementioned report.
