### ISSUE TITLE
error on distance = "oob" 

### ISSUE THREAD

**Issue by maRce10** [kogalur/randomForestSRC#23]
this is the code I ran (URF) and the error message

`urf.elm <- rfsrc(data = ap, ntree = 10000, proximity = "oob", distance = "oob")`

> Error in distance.out[k, 1:k] <- nativeOutput$distance[(count + 1):(count +  : 
>   number of items to replace is not a multiple of replacement length

my data has no NA's and only numeric variables

thanks for the cool package!

**Comment by kogalur** [comment]
Please see https://kogalur.github.io/randomForestSRC/building.html for a list of additional information that we request when logging bugs.

**Comment by ishwaran** [comment]
Please resubmit with a simple reproducible example.
