### ISSUE TITLE
Getting the raw boxplot data from "subsample" method

### ISSUE THREAD

**Issue by petteriTeikari** [kogalur/randomForestSRC#26]
I was trying to get the raw data used by the plot function `plot.subsample(model.sm.rf, ...)` in order to use the data with my other analysis functions and harmonize the figure looks. However I had some difficulties getting it

From [/src/R/plot.subsample.rfsrc.R](https://rdrr.io/cran/randomForestSRC/src/R/plot.subsample.rfsrc.R) I noticed that the plot function was calling `extract.subsample.rfsrc.local(obj = ...)` which had the `boxplot.dta` variable supposedly containing the values of each run (e.g. `B = 100`), but all the values were identical in that data frame which I did not quite understand as the standard plot functioned ok?

I managed to use the `var.jk.sel.Z` variable that contained the `mean` value with the `upper` and `lower` bounds.

![image](https://user-images.githubusercontent.com/1060514/51342456-f35c2c00-1ace-11e9-8e90-31749135a9fe.png)

Any idea why the following call did not contain the actual results from various runs?

```R
oo <- extract.subsample(x, alpha = alpha, target = target, standardize = standardize)
    boxplot.dta <- oo$boxplot.dta
```

**Comment by ishwaran** [comment]
The extract.subsample function parses the various runs and returns summary information.  It's designed to summarize and not return the run data.  From the help file:

     The function ‘extract.subsample’ conveniently extracts summary
     information from the subsampled object. It parses objects ‘rf’,
     ‘vmp’ and ‘vmpS’ returned by the function (see below for what
     these are).

**Comment by ishwaran** [comment]
The extract.subsample function will be modified in the next CRAN update (in a week or so) and will return the actual results from the various runs.  See the help file and example.  Let us know if this works.
