### ISSUE TITLE
Negative Error Rate

### ISSUE THREAD

**Issue by GeorgeRJacobs** [kogalur/randomForestSRC#3]
Hello, I was hoping to get some context as to how I could get a predicted negative error rate for a model.

**Comment by kogalur** [comment]
It's really difficult to say anything without knowing a little, actually a lot, more about your situation.  You may be hitting a  bug.  If you can provide us with a simple script and data that we can use to replicate the situation, it would help.  You haven't told us anything about the nature of your data, or the family of analysis.  What is n, what is p?  Is there any missing data in the data set.  Is this negative value encountered on the rfsrc() call or the predict() call?  Please provide us with particulars and we'll look into the matter.

**Comment by GeorgeRJacobs** [comment]
Sorry for not posting the example at the time. I was just fact finding on the error to see if anyone had encountered the error here. I will try my best to post the requisite reproducible example as soon as possible. Much thanks to the response!

**Comment by kogalur** [comment]
We are closing this issue as no response was received.
