### ISSUE TITLE
Error with distance=TRUE in rfsrc()

### ISSUE THREAD

**Issue by jeeyoungmoon0115** [kogalur/randomForestSRC#30]
Hi, 

When I tried rfsrc with distance=TRUE, there is an error like this. It looks like nativeOutput$distance is NULL.

> data(iris)
> airq.obj <- rfsrc(Ozone ~ ., data = airquality, na.action = "na.omit", distance=TRUE)
Error in distance.out[k, 1:k] <- nativeOutput$distance[(count + 1):(count +  : 
  number of items to replace is not a multiple of replacement length

> mtcars.unspv <- rfsrc(Unsupervised() ~., data = mtcars, distance=TRUE)
Error in distance.out[k, 1:k] <- nativeOutput$distance[(count + 1):(count +  : 
  number of items to replace is not a multiple of replacement length

Thank you!

**Comment by kogalur** [comment]
Thank you for the example. There was indeed a bug w.r.t. $distance output. You can find a beta build with the fix here, if it's convenient:

https://www.dropbox.com/s/85l3839v4jpnz0j/randomForestSRC_2.8.0.13.tar.gz?dl=0

We'll likely push a new build up to CRAN in a couple of weeks.

**Comment by jeeyoungmoon0115** [comment]
Thank you!!
