### ISSUE TITLE
Conditional Logistic Regression

### ISSUE THREAD

**Issue by csaiedu** [kogalur/randomForestSRC#31]
Is it possible to use randomForestSRC for evaluating a special form a cox ph regression called conditional logistic regression of the form:

```
coxph(formula = Surv(rep(1, 200L), event) ~ group + strata(id), 
    method = "exact")
```
Thanks

**Comment by ishwaran** [comment]
The "strata" option basically creates interactions with the variable "id". 

Therefore create a new data set with these interactions and run this new data set down the forest.  BTW this is called virtual twins random forests in the causal machine learning literature.
