### ISSUE TITLE
'Floor' error when factor variables specified

### ISSUE THREAD

**Issue by LKBeres** [kogalur/randomForestSRC#33]
I am using randomForestSRC to estimate the variable importance of 34 potential predictors of survival. When all of potential predictor variables are numeric (or coded as numeric) the package runs without a problem. When I add in / appropriately code factor variables as factors, I get the following error: Error in Math.factor(cens) : ‘floor’ not meaningful for factors. I have tried using the package defaults to be sure that nothing I'm specifying is causing a problem. I've tried coding all of my variables as numeric - which is incorrect. That eliminates the problem. If I specify the factor variables as factors - which is correct - I get this error. I do not know why rounding, floor, would be applied to factor variables. I have looked through the code running in the package and cannot identify where the problem is. Thank you for your assistance.

**Comment by ofonov** [comment]
I am getting the same error. An input from the developers is very appreciated.

**Comment by kogalur** [comment]
Please provide a simple reproducible example, and resubmit.  Thank you.
