### ISSUE TITLE
How to send PR?

### ISSUE THREAD

**Issue by muschellij2** [kogalur/randomForestSRC#34]
How can one send pull requests to this repository for the R package? 

I do not know this build process you have in this package, but I've contributed to many R packages.  Just wondering if you have a README on how to effectively send a PR for the package and have it checked with a CI service such as travis-ci.com.

@wshannon01 @mattrosen

**Comment by kogalur** [comment]
Thanks for your interest in contributing.  We're not yet in a position to accept PR's for the package. However, if you have suggestions on functionality, please do let us know.  Thank you.
