### ISSUE TITLE
ERROR: attempt to apply to non-function in predict using version 2.9

### ISSUE THREAD

**Issue by skvempati** [kogalur/randomForestSRC#35]
Hi, I am using the new version 2.9 and when I try to predict using a random survival forest with new test data, I am getting the error code "Attempt to apply to non-function".  I had previously used the beta code (V. 2.8.0.11) you provided in another issue (Issue #29 ) and my code ran without error. Nothing has changed in my code besides the updated package (I am using it in a Shiny app and can't use a locally installed package when deploying).  

I believe I have traced the error to lines 311 and 321 in the 'generic.predict.rfsrc' function - when assigning the variable 'sampsize'. 

The current line is 'sampsize <- round(object$sampsize(nrow(xvar)))', where object$sampsize is just an integer so it crashes (and for me, nrow(xvar) is equal to object$sampsize). I looked at previous versions of this function (v 2.8.0) and the line was 'sampsize <- object$sampsize' which seems correct. 

Is there something else in the 'predict.rfsrc' function I am missing? I am calling it exactly the same way I had been: predict(model, newdata = new_data) and this is happening with competing risk and survival models.

I REALLY need the code on CRAN to be updated as I have to present my Masters project next Friday (May 31) - do you know if debugging this error and uploading to CRAN is something you're able to do soon? Thank you!!

**Comment by kogalur** [comment]
We're not seeing this error:

data(veteran, package = "randomForestSRC")
     train <- sample(1:nrow(veteran), round(nrow(veteran) * 0.80))
     veteran.grow <- rfsrc(Surv(time, status) ~ ., veteran[train, ], ntree = 100) 
     veteran.pred <- predict(veteran.grow, veteran[-train , ])
     print(veteran.grow)
     print(veteran.pred)
                         Sample size: 110
                    Number of deaths: 105
                     Number of trees: 100
           Forest terminal node size: 15
       Average no. of terminal nodes: 4.97
No. of variables tried at each split: 3
              Total no. of variables: 6
       Resampling used to grow trees: swor
    Resample size used to grow trees: 70
                            Analysis: RSF
                              Family: surv
                      Splitting rule: logrank *random*
       Number of random split points: 10
                          Error rate: 30.3%

>      print(veteran.pred)
  Sample size of test (predict) data: 27
       Number of deaths in test data: 23
                Number of grow trees: 100
  Average no. of grow terminal nodes: 4.97
         Total no. of grow variables: 6
       Resampling used to grow trees: swor
    Resample size used to grow trees: 17
                            Analysis: RSF
                              Family: surv
                 Test set error rate: 29.43%
