### ISSUE TITLE
For Rmarkdown usability, use message() instead of cat()

### ISSUE THREAD

**Issue by wiedenhoeft** [kogalur/randomForestSRC#36]
At the moment it is near impossible to exclude text output from functions like var.select() in R markdown, since the chunk options of knitr can only suppress all text, or that output by message(), warning() and error() selectively. Please replace all instances of cat(), print(), printf() etc. by the appropriate message(), warning() and error().

**Comment by kogalur** [comment]
Well definitely look into it.  In the meantime, have you considered using verbose=FALSE in the above function call, and a couple of others that output diagnostic messages?

**Comment by wiedenhoeft** [comment]
Thanks a lot! The issue is that when having multiple function calls in a large chunk, things can get very confusing once setting chunk options does not work as expected, and we have to start changing individual calls. I appreciate having the option to *additionally* silence the output, and I am not at all suggesting to remove the verbose option! It's just that at the moment, the interaction with Rmarkdown is not what the user expects.
