### ISSUE TITLE
R session crash

### ISSUE THREAD

**Issue by FridljDa** [kogalur/randomForestSRC#387]
I am coding in R. randomForestSRC works on one machine, but crashes the R session on another machine (see enclosed screenshot). What are the strategies to debug the issue? Since the R session crashed, I do not have an error message to work from.

```
library(randomForestSRC)
data(veteran, package = "randomForestSRC")
v.obj <- rfsrc(Surv(time, status) ~ ., data = veteran, ntree = 1, block.size = 1)
```

```
sessionInfo()

R version 4.1.2 (2021-11-01) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Rocky Linux 8.8 (Green Obsidian)

Matrix products: default BLAS/LAPACK: /g/easybuild/x86_64/Rocky/8/haswell/software/FlexiBLAS/3.0.4-GCC-11.2.0/lib64/libflexiblas.so.3.0

locale: [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C[3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8[5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8[7] LC_PAPER=en_US.UTF-8       LC_NAME=C[9] LC_ADDRESS=C               LC_TELEPHONE=C[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached): [1] compiler_4.1.2 tools_4.1.2
```

I tried running on different R version on the same Linux machine. I tried redownloading the randomForestSRC package. It did not resolve the issue.

<img width="1147" alt="Screenshot 2023-08-17 at 10 47 46" src="https://github.com/kogalur/randomForestSRC/assets/25401308/b5042532-4b12-444b-82bb-04d2f79f7ad9">

**Comment by kogalur** [comment]
There is probably in an issue with your R-environment, package compilation, or package dependencies.  First, I would recommend upgrading to the latest version of R.

**Comment by FridljDa** [comment]
Thank you for answering so quickly! I agree that the issue must have something to do with the set-up on the remote machine, because it works on my local machine and used to work on the remote machine a few days ago. The issue persists on the remote machine when I switch to the latest R-version available there: 
`sessionInfo():`
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Rocky Linux 8.8 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /g/easybuild/x86_64/Rocky/8/haswell/software/FlexiBLAS/3.2.1-GCC-12.2.0/lib64/libflexiblas.so.3.2

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.2 tools_4.2.2

**Comment by kogalur** [comment]
It will take a while, but you might want to update all your installed R-packages on the remote machine. I think there's a script out there somewhere that makes this easier. We don't have a lot of dependencies, though, and I suspect it's actually a complier issue. When you install our package, is it installing pre-compiled binaries, or are you installing from source?

**Comment by FridljDa** [comment]
I am downloading it from source: `install.packages("randomForestSRC", type="source")`. I will try to update the dependent packages.

**Comment by FridljDa** [comment]
Requesting more memory via slurm solved the issue. Thank you for your prompt help!
