### ISSUE TITLE
Question: How is the Ensemble Survival Function calculated

### ISSUE THREAD

**Issue by chrisk280** [kogalur/randomForestSRC#44]
Hello,

I'm currently trying to get a deeper understanding of Random Survival Forests and how they work.
Since an individual can end up in many terminal nodes in different trees of the forest, I assume the survival function for that individual is averaged over all terminal nodes. 
https://kogalur.github.io/randomForestSRC/theory.html mentions the KM-estimator for estimating the survival function but not how the ensemble survival function is calculated.
In "Evaluating Random Forests for Survival Analysis using Prediction Error Curves" (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4194196/) it says that the ensemble survival function is derived from the ensemble CHF.
I just wanted to know what case is used in randomForestSRC. The actual equation would be the icing on the cake.

I hope this is the right place to ask such a question and that I don't bother anyone (I have a like two more questions).

Anyway, thanks for all the effort put in the papers and this R package!

Chris

**Comment by kogalur** [comment]
We mention after equation (3) and (4) that the OOB ensemble-CHF for individual "i" is arrived at by averaging the node specific curve over all trees in which "i" is OOB.  We didn't bother to mention the OOB ensemble KM, but the same technique that is used to calculate Hhat^*_e(t) is used to calculate Shat^*_e(t).  Note that while, locally, the CHF and KM estimators are related by the exponential function, this is not the case with the ensembles.

**Comment by chrisk280** [comment]
Thanks for your fast reply!
So for an individual i we have the
- ensemble survival function, 
- OOB ensemble survival function,
- ensemble CHF
- OOB ensemble CHF.
For the ensemble survival function/ensemble CHF, all the terminal nodes are taken where i is part of and then the corresponding terminal node estimators are averaged to get the results for i.
For the OOB ensemble estimates, we drop OOB data (where i is part of) down the corresponding trees and average over the the terminal nodes where i ends up in.
Did I get that right? 
Then I have a follow-up question:
What are the OOB ensemble estimates used for and how can I interpret them?
Because by intuition, if I was interested in the survival of an individual, I would just average over the in-bag results.
(My other "big" questions is related to imbalanced data in survival settings, shall I ask it here or open a new issue?)

Thanks in advance!

Chris

**Comment by ishwaran** [comment]
This person wants a statistical tutorial but this is a forum for software.  Just send him to read the following articles

http://web.ccs.miami.edu/~hishwaran/papers/IKBL.AOAS.pdf

http://web.ccs.miami.edu/~hishwaran/papers/WileySTAT-randomsurvivalforest-20180820.pdf

**Comment by ishwaran** [comment]
Regarding inbalanced data , once again it’s clear he’s not read the help file and done due diligence 

Send him to read

http://web.ccs.miami.edu/~hishwaran/papers/OI_PatternRecognition_2019.pdf

**Comment by chrisk280** [comment]
I'm sorry for asking at the wrong place. Thank you for posting the links for a further read.

**Comment by chrisk280** [comment]
http://web.ccs.miami.edu/~hishwaran/papers/WileySTAT-randomsurvivalforest-20180820.pdf really helped
Again, sorry for bothering you with questions that don't belong here.
