### ISSUE TITLE
Extract the brier score for survival random forest object

### ISSUE THREAD

**Issue by ShengnanHuang9** [kogalur/randomForestSRC#45]
Hi there,

I would like to extract the Brier score directly from the rf1 object by modifying the source code of `plot.survival.rfsrc`, in a way of returning the dataset `brier.score` and `crps`. However, it gives me an error that  `could not find function "get.event.info"` and I cannot find the source code. Could you please explain the function of `get.event.info` usage or let `plot.survival.rfsrc` also output the Brier score and crps?

Btw, the reason why I cannot use pec::pec to get the brier score is that there are missing in my test set. When the pec::predictSurvProb.rfsrc in pec::pec works on the `rfsrc `object, you can see in the function `predict` below, 'na.action = "na.impute"' is not there, hence, it can only output the predicted values for non-missing, which will give an error. 

```
predictSurvProb.rfsrc <- function(object, newdata, times, ...){
    ptemp <- predict(object,newdata=newdata,importance="none",...)$survival
    pos <- prodlim::sindex(jump.times=object$time.interest,eval.times=times)
    p <- cbind(1,ptemp)[,pos+1,drop=FALSE]
    if (NROW(p) != NROW(newdata) || NCOL(p) != length(times))
        stop(paste("\nPrediction matrix has wrong dimensions:\nRequested newdata x times: ",NROW(newdata)," x ",length(times),"\nProvided prediction matrix: ",NROW(p)," x ",NCOL(p),"\n\n",sep=""))
    p
} 

```
Thanks in advance!
Shengnan

**Comment by bonedi** [comment]
You can select the brier score from the object returned by plot.survival.rfsrc()
if `rsf` is your random survival forrest, you can get the Brier score simply by:
`
plt <- plot.survival.rfsrc(rsf)
bs <- plt$bs.all
`
The same you can do with crps by seletcing `plt$crps.all`
