### ISSUE TITLE
Fatal Error possibly caused by factor in tbl_df

### ISSUE THREAD

**Issue by yilunsun** [kogalur/randomForestSRC#455]
Hello,

I have encountered fatal errors when trying to use random survival forest with factor predictors in a tibble. A minimal reproducible example is:

`
library(randomForestSRC)

data(wihs, package = "randomForestSRC")
wihs <- dplyr::as_tibble(wihs)
wihs$black <- factor(wihs$black)
plot(tune.nodesize(Surv(time, status) ~ ., wihs, trace = TRUE)$err)
`

**Comment by ishwaran** [comment]
Convert the tibble to a data.frame:

`wihs <- data.frame(wihs)`

This issue has been discussed before https://github.com/kogalur/randomForestSRC/issues/12
