### ISSUE TITLE
failed attempt to build on mac osx with openmp

### ISSUE THREAD

**Issue by chillydog** [kogalur/randomForestSRC#48]
Hi,

I am trying to complile randomForestSRC for use of OpenMP following the instructions at

https://kogalur.github.io/randomForestSRC/building.html

As you can see, below, I have the clang8, fortran 6.1.0, ant 1.10.7, and java 1.8.0 (Mac OS Mojave 10.14.6).  The problem appears to be a non-existent directory when attempting ``ant source-cran’’.  Perhaps I’ve got the build.xml file in the wrong directory to begin with.  Not sure.  Advice appreciated.  Best, -- Jay

math172m-01:tmp jay$ echo $PATH
/usr/local/ant/bin:/usr/local/gfortran/bin:/usr/local/clang8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin

math172m-01:tmp jay$ clang --version
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /usr/local/clang8/bin

math172m-01:tmp jay$ gfortran --version
GNU Fortran (GCC) 6.1.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

math172m-01:tmp jay$ ant -version
Apache Ant(TM) version 1.10.7 compiled on September 1 2019

math172m-01:tmp jay$ java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

math172m-01:tmp jay$ ant source-cran
Buildfile: /Users/jay/Desktop/tmp/build.xml

init:
     [echo] --------- randomForestSRC ---------
     [echo] 
     [echo] Version:     2.9.1
     [echo] Build:       bld20190708a
     [echo] 
     [echo]   Date:      2019-10-04
     [echo]   Time:      04:07:42
     [echo] 
     [echo] Platform Details:
     [echo]   OS name    Mac OS X
     [echo]   OS version 10.14.6
     [echo]   OS arch    x86_64
     [echo]   Java arch  64

clean-cran:
   [delete] Deleting directory /Users/jay/Desktop/tmp/target/cran

source-cran:
    [mkdir] Created dir: /Users/jay/Desktop/tmp/target/cran
    [mkdir] Created dir: /Users/jay/Desktop/tmp/target/cran/randomForestSRC
    [mkdir] Created dir: /Users/jay/Desktop/tmp/target/cran/randomForestSRC/inst
    [mkdir] Created dir: /Users/jay/Desktop/tmp/target/cran/randomForestSRC/data
    [mkdir] Created dir: /Users/jay/Desktop/tmp/target/cran/randomForestSRC/man
    [mkdir] Created dir: /Users/jay/Desktop/tmp/target/cran/randomForestSRC/R
    [mkdir] Created dir: /Users/jay/Desktop/tmp/target/cran/randomForestSRC/src

BUILD FAILED
/Users/jay/Desktop/tmp/build.cran.xml:29: /Users/jay/Desktop/tmp/src/main/resources/cran does not exist.

Total time: 0 seconds
math172m-01:tmp jay$

**Comment by kogalur** [comment]
You should check that ~/Desktop/tmp/src exists.  It appears you might have corrupted your source directory tree.
