### ISSUE TITLE
Multivariate with real Ys

### ISSUE THREAD

**Issue by angelini75** [kogalur/randomForestSRC#49]
Hi there,

I am interested in multivariate prediction of real Ys. However, I would like to know whether the prediction method takes into account the joint distribution of the Ys. The splitting function (Weighted variance splitting) is explained for one single Y_{i}. Does this function change when the model is multivariate?
Would you recommend any particular approach to estimate prediction intervals for this approach?

**Comment by kogalur** [comment]
The multivariate splitting rule does not take into account the correlation of the Y's - to be clear, it is not a Mahalanobis distance.  Rather it is an averaged composite of the split-statistics for each of the individual Y's.
