### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by verne91** [kogalur/randomForestSRC#5]
> install.packages("randomForestSRC")
Installing package into ‘/home/cnsun/R/x86_64-redhat-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/src/contrib/randomForestSRC_2.5.1.tar.gz'
Content type 'application/x-gzip' length 903705 bytes (882 KB)
==================================================
downloaded 882 KB

* installing *source* package ‘randomForestSRC’ ...
** package ‘randomForestSRC’ successfully unpacked and MD5 sums checked
checking for gcc... gcc -m64 -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -m64 -std=gnu99 accepts -g... yes
checking for gcc -m64 -std=gnu99 option to accept ISO C89... none needed
checking for gcc -m64 -std=gnu99 option to support OpenMP... -fopenmp
configure: creating ./config.status
config.status: creating src/Makevars
** libs
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -fopenmp  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c R_init_randomForestSRC.c -o R_init_randomForestSRC.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG   -I/usr/local/include  -fopenmp  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c randomForestSRC.c -o randomForestSRC.o
randomForestSRC.c: In function ‘updateProximity’:
randomForestSRC.c:19867: error: expected end of line before ‘update’
randomForestSRC.c:19872: error: expected end of line before ‘update’
make: *** [randomForestSRC.o] Error 1
ERROR: compilation failed for package ‘randomForestSRC’
* removing ‘/home/cnsun/R/x86_64-redhat-linux-gnu-library/3.4/randomForestSRC’

The downloaded source packages are in
	‘/tmp/RtmpA1tGwr/downloaded_packages’
Warning message:
In install.packages("randomForestSRC") :
  installation of package ‘randomForestSRC’ had non-zero exit status

**Comment by kogalur** [comment]
Your GCC installation is being detected by the CRAN packaging protocols as being OpenMP compliant, but your compiler apparently does not understand: 

#pragma omp atomic update

I would recommend that you upgrade your GCC compiler, or settle for running RF-SRC in serial mode.  If the latter is an acceptable solution, delete the configure and configure.ac files in the root directory of the source package and then install as usual.

**Comment by verne91** [comment]
Thanks! I install it successfully after updating the gcc.
