### ISSUE TITLE
How to get imputed data when nimpute > 1?

### ISSUE THREAD

**Issue by bonedi** [kogalur/randomForestSRC#55]
How do I get the imputed data when I choose nimpute bigger than 1?
If I use `nimpute = 1`, i can simply get all imputed data with `rsf1$imputed.data` but when e.g. `nimpute = 5`, then `rsf5$imputed.data` is NULL. 
I have seen that there aren't NA's anymore in `rsf5$xvar`. Are these the imputed values? I'm not sure, because the values in `rsf5$xvar$` are imputed worse than they are in `rsf1$imputed.data`. Meaning that more iterations yield worse imputation. 
I used the first 312 observations of the pbc dataset. 
```
i_train <- sample(1:nrow(pbc), round(.8 * nrow(pbc)))  
train <- pbc[i_train,]  
train[ii,"bili"] <- NA  
rsf1 <- randomForestSRC::rfsrc(Surv(time, status)~., data = train, ntree = 1000,
                                   importance = T, splitrule = "logrank", nimpute = 1,
                                   seed = s, na.action = "na.impute")
rsf5 <- randomForestSRC::rfsrc(Surv(time, status)~., data = train, ntree = 1000,
                                   importance = T, splitrule = "logrank",
                                   seed = s, na.action = "na.impute",  nimpute = 5)
```

**Comment by ishwaran** [comment]
From the help file:         

        "When iterated, at the completion of each iteration, missing data
          is imputed using OOB non-missing terminal node data which is
          then used as input to grow a new forest.  A side side effect
          of iteration is that missing values in the returned objects
          ‘xvar’, ‘yvar’ are replaced by imputed values. "

In other words, the original data is overlaid by the missing data.
