### ISSUE TITLE
resampling method?

### ISSUE THREAD

**Issue by mollmatt** [kogalur/randomForestSRC#56]
Hi, I have several rfsrc objects that have worked without a problem for awhile.  I revisited an old analysis, and when I type the object name into R, I get the following:

   Sample size: 1974
                    Number of deaths: 479
                     Number of trees: 20000
           Forest terminal node size: 15
       Average no. of terminal nodes: 118.7242
No. of variables tried at each split: 5
              Total no. of variables: 17
       Resampling used to grow trees: swr
Error in cat("    Resample size used to grow trees: ", round(x$forest$sampsize(x$n)),  : 
  attempt to apply non-function

Because of this error, I'm not able to use the object for prediction or anything else.  Can you please help?
Thank you in advance.

**Comment by kogalur** [comment]
Unfortunately, we have not maintained backward compatibility with previous version of RF-SRC.  You will have to re-run your analysis.  As a side note, you might want to run tune.rfsrc() on it first.  It's highly unlikely that you need 20,000 trees in the model.  You might even need far less than 1000.

**Comment by mollmatt** [comment]
Okay, thanks for your help.

Matt
