### ISSUE TITLE
hierarchical feature selection?

### ISSUE THREAD

**Issue by nick-youngblut** [kogalur/randomForestSRC#57]
In biology, features are often hierarchically related (eg., `genes => pathways => species => genera => ... => phyla`). Currently, most researchers just pick a level in the hierarchy for RF learning (or for other ML learners). However, one does not really know the "best" granularity to use, and at least for taxonomy, the levels of granularity are somewhat arbitrary and inconsistent (eg., a `family` can have the same phylogenetic diversity as a `genus` or `order` in other lineages). Selecting a very granular level (eg., genes) can lead to high numbers of zeros in the feature table, so most features become uninformative, while alternatively selecting a course level can aggregate truly predictive features (eg., Species 1) with noise features (eg., Species 2 + 3) and thus reduce predictive power. 

Therefore, it would be helpful if one could select features from anywhere in the hierarchy during the creation of each tree, but redundant features in a lineage are not included (eg., if one species in genus, then the genus and species cannot both be used, since they contain the same information). If a feature is selected that has children features, then those children cannot also be selected for that decision tree. The same goes for the parents of that selected feature. In other words, each tree can include only one feature per lineage in the hierarchy (the `root` feature is never selected for obvious reasons). The user would provide a tree representing the hierarchical associations among features. Features that don't fall into the hierarchical relationship (eg., soil pH, person age or disease status) can just be children of the root in the tree (separate lineages). 

I was hoping that I could just fork `randomForestSRC` and implement this myself, but modifying the C code is WAY beyond my abilities. Do you think that this feature selection algorithm makes sense, and is there any chance that it could be implemented in `randomForestSRC`? I've tried to find a RF implementation that uses this approach for hierarchical data, but I haven't seen any.

**Comment by ishwaran** [comment]
This is something that others have pointed out and it's an interesting idea worth exploring.  However it is non-trivial and not possible to implement currently without major restructuring/rewriting of code.  Perhaps in the future we will revisit this idea.
