### ISSUE TITLE
imbalanced.rfsrc error: ``An error has occurred in the grow algorithm.  Please turn trace on for further analysis.''

### ISSUE THREAD

**Issue by chillydog** [kogalur/randomForestSRC#58]
Hi,

I'm running imbalanced.rfsrc using rfq (default) and optimize=TRUE (see R Code below), and I get some sort of memory error (see Output below).  In my original posting of this message, I thought my process was running out of memory (128GB requested, see SLURM Batch file, below), and SLURM usually handles this, but the error does not look like a typical SLURM out of memory error, so I thought I'd pass this along in case there is a bug.  (CentOS on a Linux cluster)

Any help is appreciated.  In the meantime, I'll run the code again on a node with more memory to see if this fixes things.

(UPDATE 1: I ran with more memory.  And, I get a _similar_ error, BUT now the error message includes: "An error has occurred in the grow algorithm.  Please turn trace on for further analysis."  See Output for UPDATE 1, below.  So, I guess I'll see what happens when I set trace=TRUE and get back with you...)

(UPDATE 2: After running with trace=TRUE, I get the same sort or error that includes "An error has occurred in the grow algorithm.  Please turn trace on for further analysis."   See Output for UPDATE 2, below.)

After these updates, I'm not sure if it's an out of memory issue (which, according to my brief experience, SLURM typically reports much differently than the messages I see here), or if its a bug in imbalanced.rfsrc.  Again, help is appreciated.  Thanks for the package!

Best,

Jay

SLURM Batch file (In UPDATES 1 and 2, further below, I ran with more memory: 380GB!  Updated batch files not shown):

#!/bin/bash
#SBATCH --job-name=m10wc5
#SBATCH --output=/scratch/jjb485/neonatal/moth10wcodes/moth10wcodes5.txt
#SBATCH --time=1-0:00:00
#SBATCH --chdir=/scratch/jjb485/neonatal/moth10wcodes
#SBATCH --cpus-per-task=28
#SBATCH --ntasks=1
#SBATCH --nodes=1-1
#SBATCH --mem=128G

module load R/latest
srun Rscript /home/jjb485/neonatal/moth10wcodes/moth10wcodes5.R

Original R Code (The output from UPDATE 1 asked me to turn on trace=TRUE.  Results are shown in UPDATE 2, further below.  Updated R code with trace=TRUE not shown)

## moth10wcodes5.R
library(parallel)
library(randomForestSRC, lib.loc="/home/jjb485/Rlib")
detectCores()
options(rf.cores=detectCores(), mc.cores=detectCores())
load("/home/jjb485/neonatal/moth10wcodes/motherIDC10comorbNO2.df.RData")
print("data loaded")
system.time(moth10wcodes5NO2.rfsrc<- imbalanced(OpiateDependence ~ .,
                                               data=motherIDC10comorbNO2.df,
                                               optimize=TRUE,
                                               do.trace=60))

Output:

 randomForestSRC 2.9.1 
 
 Type rfsrc.news() to see new features, changes, and bug fixes. 
 

[1] 32
[1] "data loaded"

Trees Grown:       4,    Time Remaining (sec):   45689
Trees Grown:      21,    Time Remaining (sec):   17874
Trees Grown:      37,    Time Remaining (sec):   15136
Trees Grown:      54,    Time Remaining (sec):   13694
Trees Grown:      77,    Time Remaining (sec):   12528
Trees Grown:      97,    Time Remaining (sec):   11762
Trees Grown:     116,    Time Remaining (sec):   11313
Trees Grown:     132,    Time Remaining (sec):   11255
Trees Grown:     147,    Time Remaining (sec):   11257
Trees Grown:     161,    Time Remaining (sec):   11339
Trees Grown:     180,    Time Remaining (sec):   11030
Trees Grown:     195,    Time Remaining (sec):   11019
Trees Grown:     213,    Time Remaining (sec):   10874
Trees Grown:     231,    Time Remaining (sec):   10705
Trees Grown:     250,    Time Remaining (sec):   10593
Trees Grown:     266,    Time Remaining (sec):   10556
Trees Grown:     282,    Time Remaining (sec):   10564
Trees Grown:     300,    Time Remaining (sec):   10413
Trees Grown:     316,    Time Remaining (sec):   10346
Trees Grown:     334,    Time Remaining (sec):   10210
Trees Grown:     348,    Time Remaining (sec):   10220
Trees Grown:     368,    Time Remaining (sec):   10042
Trees Grown:     385,    Time Remaining (sec):    9999
Trees Grown:     406,    Time Remaining (sec):    9795
Trees Grown:     423,    Time Remaining (sec):    9711
Trees Grown:     445,    Time Remaining (sec):    9520
Trees Grown:     463,    Time Remaining (sec):    9420
Trees Grown:     474,    Time Remaining (sec):    9492
Trees Grown:     496,    Time Remaining (sec):    9355
Trees Grown:     509,    Time Remaining (sec):    9367
Trees Grown:     528,    Time Remaining (sec):    9266
Trees Grown:     544,    Time Remaining (sec):    9224
Trees Grown:     561,    Time Remaining (sec):    9187
Trees Grown:     580,    Time Remaining (sec):    9075
Trees Grown:     597,    Time Remaining (sec):    9005
Trees Grown:     612,    Time Remaining (sec):    8967
Trees Grown:     633,    Time Remaining (sec):    8822
Trees Grown:     644,    Time Remaining (sec):    8883
Trees Grown:     662,    Time Remaining (sec):    8826
Trees Grown:     682,    Time Remaining (sec):    8708
Trees Grown:     698,    Time Remaining (sec):    8651
Trees Grown:     715,    Time Remaining (sec):    8578
Trees Grown:     731,    Time Remaining (sec):    8521
Trees Grown:     751,    Time Remaining (sec):    8428
Trees Grown:     770,    Time Remaining (sec):    8335
Trees Grown:     785,    Time Remaining (sec):    8293
Trees Grown:     800,    Time Remaining (sec):    8253
Trees Grown:     817,    Time Remaining (sec):    8206
Trees Grown:     840,    Time Remaining (sec):    8057
Trees Grown:     855,    Time Remaining (sec):    8024
Trees Grown:     872,    Time Remaining (sec):    7959
Trees Grown:     887,    Time Remaining (sec):    7924
Trees Grown:     903,    Time Remaining (sec):    7878
Trees Grown:     920,    Time Remaining (sec):    7807
Trees Grown:     937,    Time Remaining (sec):    7744
Trees Grown:     951,    Time Remaining (sec):    7712
Trees Grown:     968,    Time Remaining (sec):    7641
Trees Grown:     986,    Time Remaining (sec):    7562
Trees Grown:    1005,    Time Remaining (sec):    7470
Trees Grown:    1022,    Time Remaining (sec):    7407
Trees Grown:    1038,    Time Remaining (sec):    7353
Trees Grown:    1061,    Time Remaining (sec):    7225
Trees Grown:    1075,    Time Remaining (sec):    7190
Trees Grown:    1091,    Time Remaining (sec):    7136
Trees Grown:    1112,    Time Remaining (sec):    7033
Trees Grown:    1127,    Time Remaining (sec):    6996
Trees Grown:    1148,    Time Remaining (sec):    6891
Trees Grown:    1166,    Time Remaining (sec):    6830
Trees Grown:    1186,    Time Remaining (sec):    6736
Trees Grown:    1198,    Time Remaining (sec):    6717
Trees Grown:    1216,    Time Remaining (sec):    6645
Trees Grown:    1238,    Time Remaining (sec):    6543
Trees Grown:    1253,    Time Remaining (sec):    6506
Trees Grown:    1273,    Time Remaining (sec):    6420
Trees Grown:    1288,    Time Remaining (sec):    6377
Trees Grown:    1308,    Time Remaining (sec):    6285
Trees Grown:    1326,    Time Remaining (sec):    6222
Trees Grown:    1343,    Time Remaining (sec):    6157
Trees Grown:    1360,    Time Remaining (sec):    6091
Trees Grown:    1377,    Time Remaining (sec):    6026
Trees Grown:    1395,    Time Remaining (sec):    5958
Trees Grown:    1409,    Time Remaining (sec):    5916
Trees Grown:    1423,    Time Remaining (sec):    5874
Trees Grown:    1443,    Time Remaining (sec):    5786
Trees Grown:    1459,    Time Remaining (sec):    5736
Trees Grown:    1476,    Time Remaining (sec):    5677
Trees Grown:    1493,    Time Remaining (sec):    5618
Trees Grown:    1510,    Time Remaining (sec):    5559
Trees Grown:    1529,    Time Remaining (sec):    5491
Trees Grown:    1547,    Time Remaining (sec):    5418
Trees Grown:    1563,    Time Remaining (sec):    5360
Trees Grown:    1582,    Time Remaining (sec):    5283
Trees Grown:    1602,    Time Remaining (sec):    5199<simpleError: C stack usage  80241047060 is too close to the limit>

 *** caught segfault ***
address (nil), cause 'unknown'

 *** caught segfault ***
address 0x29fa, cause 'memory not mapped'
Timing stopped at: 1.649e+05 6595 7161
Execution halted
Error in split(.encode_numeric_version(c(e1, e2)), rep.int(c(1L, 2L),  : 
  SET_VECTOR_ELT() can only be applied to a 'list', not a 'character'
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
srun: error: cn12: task 0: Exited with exit code 1

Output for UPDATE 1 (output from run with more memory (380GB).  Now I get "Please turn on trace..." in the output...see Output for UPDATE 2, further below.):

 randomForestSRC 2.9.1 
 
 Type rfsrc.news() to see new features, changes, and bug fixes. 
 

[1] 32
[1] "data loaded"

Trees Grown:       5,    Time Remaining (sec):   37737
Trees Grown:      24,    Time Remaining (sec):   16368
Trees Grown:      40,    Time Remaining (sec):   14356
Trees Grown:      63,    Time Remaining (sec):   11888
Trees Grown:      80,    Time Remaining (sec):   11863
Trees Grown:      96,    Time Remaining (sec):   11677
Trees Grown:     117,    Time Remaining (sec):   11015
Trees Grown:     131,    Time Remaining (sec):   11214
Trees Grown:     147,    Time Remaining (sec):   11141
Trees Grown:     168,    Time Remaining (sec):   10958
Trees Grown:     187,    Time Remaining (sec):   10726
Trees Grown:     201,    Time Remaining (sec):   10779
Trees Grown:     220,    Time Remaining (sec):   10716
Trees Grown:     238,    Time Remaining (sec):   10561
Trees Grown:     255,    Time Remaining (sec):   10561
Trees Grown:     273,    Time Remaining (sec):   10419
Trees Grown:     286,    Time Remaining (sec):   10505
Trees Grown:     306,    Time Remaining (sec):   10301
Trees Grown:     319,    Time Remaining (sec):   10346
Trees Grown:     336,    Time Remaining (sec):   10252
Trees Grown:     352,    Time Remaining (sec):   10277
Trees Grown:     366,    Time Remaining (sec):   10277
Trees Grown:     381,    Time Remaining (sec):   10250
Trees Grown:     400,    Time Remaining (sec):   10121
Trees Grown:     418,    Time Remaining (sec):   10013
Trees Grown:     437,    Time Remaining (sec):    9936
Trees Grown:     454,    Time Remaining (sec):    9859
Trees Grown:     470,    Time Remaining (sec):    9835
Trees Grown:     487,    Time Remaining (sec):    9753
Trees Grown:     505,    Time Remaining (sec):    9640
Trees Grown:     521,    Time Remaining (sec):    9574
Trees Grown:     537,    Time Remaining (sec):    9509
Trees Grown:     554,    Time Remaining (sec):    9462
Trees Grown:     570,    Time Remaining (sec):    9422
Trees Grown:     588,    Time Remaining (sec):    9316
Trees Grown:     604,    Time Remaining (sec):    9267
Trees Grown:     619,    Time Remaining (sec):    9240
Trees Grown:     639,    Time Remaining (sec):    9112
Trees Grown:     655,    Time Remaining (sec):    9051
Trees Grown:     669,    Time Remaining (sec):    9025
Trees Grown:     684,    Time Remaining (sec):    8980
Trees Grown:     701,    Time Remaining (sec):    8911
Trees Grown:     712,    Time Remaining (sec):    8937
Trees Grown:     727,    Time Remaining (sec):    8899
Trees Grown:     739,    Time Remaining (sec):    8904
Trees Grown:     761,    Time Remaining (sec):    8748
Trees Grown:     775,    Time Remaining (sec):    8720
Trees Grown:     789,    Time Remaining (sec):    8682
Trees Grown:     805,    Time Remaining (sec):    8628
Trees Grown:     824,    Time Remaining (sec):    8517
Trees Grown:     841,    Time Remaining (sec):    8436
Trees Grown:     856,    Time Remaining (sec):    8386
Trees Grown:     874,    Time Remaining (sec):    8295
Trees Grown:     892,    Time Remaining (sec):    8213
Trees Grown:     908,    Time Remaining (sec):    8154
Trees Grown:     926,    Time Remaining (sec):    8077
Trees Grown:     942,    Time Remaining (sec):    8021
Trees Grown:     956,    Time Remaining (sec):    7997
Trees Grown:     979,    Time Remaining (sec):    7853
Trees Grown:     995,    Time Remaining (sec):    7801
Trees Grown:    1013,    Time Remaining (sec):    7713
Trees Grown:    1027,    Time Remaining (sec):    7672
Trees Grown:    1045,    Time Remaining (sec):    7602
Trees Grown:    1059,    Time Remaining (sec):    7559
Trees Grown:    1075,    Time Remaining (sec):    7504
Trees Grown:    1089,    Time Remaining (sec):    7466
Trees Grown:    1107,    Time Remaining (sec):    7384
Trees Grown:    1121,    Time Remaining (sec):    7341
Trees Grown:    1140,    Time Remaining (sec):    7250
Trees Grown:    1154,    Time Remaining (sec):    7213
Trees Grown:    1172,    Time Remaining (sec):    7128
Trees Grown:    1184,    Time Remaining (sec):    7103
Trees Grown:    1201,    Time Remaining (sec):    7033
Trees Grown:    1221,    Time Remaining (sec):    6931
Trees Grown:    1236,    Time Remaining (sec):    6877
Trees Grown:    1250,    Time Remaining (sec):    6831
Trees Grown:    1268,    Time Remaining (sec):    6755
Trees Grown:    1283,    Time Remaining (sec):    6709
Trees Grown:    1295,    Time Remaining (sec):    6681
Trees Grown:    1309,    Time Remaining (sec):    6635
Trees Grown:    1326,    Time Remaining (sec):    6563
Trees Grown:    1340,    Time Remaining (sec):    6517
Trees Grown:    1355,    Time Remaining (sec):    6460
Trees Grown:    1372,    Time Remaining (sec):    6390
Trees Grown:    1388,    Time Remaining (sec):    6337
Trees Grown:    1407,    Time Remaining (sec):    6254
Trees Grown:    1424,    Time Remaining (sec):    6181
Trees Grown:    1444,    Time Remaining (sec):    6089
Trees Grown:    1459,    Time Remaining (sec):    6032
Trees Grown:    1479,    Time Remaining (sec):    5937
Trees Grown:    1497,    Time Remaining (sec):    5858
Trees Grown:    1513,    Time Remaining (sec):    5798
Trees Grown:    1534,    Time Remaining (sec):    5696<simpleError: C stack usage  911237699092 is too close to the limit>

 *** caught segfault ***
address 0x2e0000007d, cause 'memory not mapped'
Error in rfsrc(formula = OpiateDependence ~ ., data = list(OpiateDependence = c(1L,  : 
  An error has occurred in the grow algorithm.  Please turn trace on for further analysis.
Calls: system.time -> imbalanced -> do.call -> rfsrc
Timing stopped at: 1.617e+05 6466 6095
Execution halted
srun: error: cn13: task 0: Exited with exit code 1

Output for UPDATE 2 (380GB and trace=TRUE; updated code not shown):

 randomForestSRC 2.9.1 
 
 Type rfsrc.news() to see new features, changes, and bug fixes. 
 

[1] 32
[1] "data loaded"

Trees Grown:       4,    Time Remaining (sec):   49434
Trees Grown:      24,    Time Remaining (sec):   16244
Trees Grown:      45,    Time Remaining (sec):   13068
Trees Grown:      63,    Time Remaining (sec):   12494
Trees Grown:      82,    Time Remaining (sec):   11744
Trees Grown:      94,    Time Remaining (sec):   12088
Trees Grown:     111,    Time Remaining (sec):   11973
Trees Grown:     127,    Time Remaining (sec):   11922
Trees Grown:     147,    Time Remaining (sec):   11471
Trees Grown:     167,    Time Remaining (sec):   11129
Trees Grown:     183,    Time Remaining (sec):   11145
Trees Grown:     201,    Time Remaining (sec):   10960
Trees Grown:     219,    Time Remaining (sec):   10794
Trees Grown:     236,    Time Remaining (sec):   10682
Trees Grown:     253,    Time Remaining (sec):   10565
Trees Grown:     270,    Time Remaining (sec):   10465
Trees Grown:     287,    Time Remaining (sec):   10361
Trees Grown:     305,    Time Remaining (sec):   10233
Trees Grown:     320,    Time Remaining (sec):   10218
Trees Grown:     340,    Time Remaining (sec):   10046
Trees Grown:     356,    Time Remaining (sec):    9997
Trees Grown:     376,    Time Remaining (sec):    9827
Trees Grown:     392,    Time Remaining (sec):    9774
Trees Grown:     410,    Time Remaining (sec):    9691
Trees Grown:     430,    Time Remaining (sec):    9533
Trees Grown:     443,    Time Remaining (sec):    9565
Trees Grown:     460,    Time Remaining (sec):    9487
Trees Grown:     479,    Time Remaining (sec):    9395
Trees Grown:     496,    Time Remaining (sec):    9350
Trees Grown:     517,    Time Remaining (sec):    9188
Trees Grown:     532,    Time Remaining (sec):    9167
Trees Grown:     547,    Time Remaining (sec):    9140
Trees Grown:     563,    Time Remaining (sec):    9091
Trees Grown:     580,    Time Remaining (sec):    9038
Trees Grown:     600,    Time Remaining (sec):    8928
Trees Grown:     622,    Time Remaining (sec):    8771
Trees Grown:     638,    Time Remaining (sec):    8734
Trees Grown:     656,    Time Remaining (sec):    8665
Trees Grown:     667,    Time Remaining (sec):    8706
Trees Grown:     680,    Time Remaining (sec):    8721
Trees Grown:     703,    Time Remaining (sec):    8561
Trees Grown:     715,    Time Remaining (sec):    8591
Trees Grown:     735,    Time Remaining (sec):    8475
Trees Grown:     753,    Time Remaining (sec):    8392
Trees Grown:     773,    Time Remaining (sec):    8283
Trees Grown:     790,    Time Remaining (sec):    8225
Trees Grown:     814,    Time Remaining (sec):    8076
Trees Grown:     825,    Time Remaining (sec):    8097
Trees Grown:     848,    Time Remaining (sec):    7961
Trees Grown:     867,    Time Remaining (sec):    7883
Trees Grown:     887,    Time Remaining (sec):    7793
Trees Grown:     904,    Time Remaining (sec):    7731
Trees Grown:     922,    Time Remaining (sec):    7652
Trees Grown:     942,    Time Remaining (sec):    7560
Trees Grown:     960,    Time Remaining (sec):    7487
Trees Grown:     975,    Time Remaining (sec):    7444
Trees Grown:     993,    Time Remaining (sec):    7372
Trees Grown:    1009,    Time Remaining (sec):    7323
Trees Grown:    1021,    Time Remaining (sec):    7312
Trees Grown:    1041,    Time Remaining (sec):    7214
Trees Grown:    1058,    Time Remaining (sec):    7148
Trees Grown:    1072,    Time Remaining (sec):    7121
Trees Grown:    1094,    Time Remaining (sec):    7006
Trees Grown:    1114,    Time Remaining (sec):    6921
Trees Grown:    1129,    Time Remaining (sec):    6881
Trees Grown:    1145,    Time Remaining (sec):    6832
Trees Grown:    1159,    Time Remaining (sec):    6799
Trees Grown:    1177,    Time Remaining (sec):    6732
Trees Grown:    1196,    Time Remaining (sec):    6652
Trees Grown:    1214,    Time Remaining (sec):    6580
Trees Grown:    1235,    Time Remaining (sec):    6482
Trees Grown:    1253,    Time Remaining (sec):    6410
Trees Grown:    1269,    Time Remaining (sec):    6356
Trees Grown:    1287,    Time Remaining (sec):    6285
Trees Grown:    1303,    Time Remaining (sec):    6236
Trees Grown:    1317,    Time Remaining (sec):    6197
Trees Grown:    1332,    Time Remaining (sec):    6149
Trees Grown:    1351,    Time Remaining (sec):    6070
Trees Grown:    1368,    Time Remaining (sec):    6014
Trees Grown:    1385,    Time Remaining (sec):    5950
Trees Grown:    1401,    Time Remaining (sec):    5905
Trees Grown:    1420,    Time Remaining (sec):    5825
Trees Grown:    1433,    Time Remaining (sec):    5792
Trees Grown:    1452,    Time Remaining (sec):    5712
Trees Grown:    1465,    Time Remaining (sec):    5686
Trees Grown:    1481,    Time Remaining (sec):    5629
Trees Grown:    1499,    Time Remaining (sec):    5560
Trees Grown:    1515,    Time Remaining (sec):    5506
Trees Grown:    1530,    Time Remaining (sec):    5463
Trees Grown:    1547,    Time Remaining (sec):    5398
Trees Grown:    1562,    Time Remaining (sec):    5347
Trees Grown:    1576,    Time Remaining (sec):    5307
Trees Grown:    1598,    Time Remaining (sec):    5211<simpleError: C stack usage  644480779796 is too close to the limit>
Error in rfsrc(formula = OpiateDependence ~ ., data = list(OpiateDependence = c(1L,  : 
  An error has occurred in the grow algorithm.  Please turn trace on for further analysis.
Calls: system.time -> imbalanced -> do.call -> rfsrc
Timing stopped at: 1.837e+05 7646 6064
Execution halted

 *** caught segfault ***
address 0x7f7065308541, cause 'memory not mapped'

Traceback:
 1: file.exists(file.path(package.lib, package, "NAMESPACE"))
 2: packageHasNamespace(package, package.lib)
 3: loadNamespace(name)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(loadNamespace(name), error = function(e) stop(e))
 8: getNamespace(ns)
 9: asNamespace(ns)
10: getExportedValue(pkg, name)
11: tools::SIGKILL
12: cleanup(kill = tools::SIGKILL, detach = TRUE, shutdown = TRUE)
13: (function (e) cleanup(kill = tools::SIGKILL, detach = TRUE, shutdown = TRUE))(<environment>)
An irrecoverable exception occurred. R is aborting now ...
srun: error: cn14: task 0: Segmentation fault

**Comment by kogalur** [comment]
You might want to take a look at issue #62 which is related to +/- Inf values in the data.  Otherwise, it's impossible to reproduce your error without your data, and/or more information on dimensionality.

**Comment by ev000ans** [comment]
I was getting very similar errors with rfsrc() a few months back.  Setting do.trace=FALSE seemed to fix it.

**Comment by kogalur** [comment]
Thank you for the comment!  Fixing do.trace is on our to-do list.  It's passing messages from C to R to affect the trace, and there appears to be an issue when running an OpenMP compliant build.
