### ISSUE TITLE
Estimate memory need for this software

### ISSUE THREAD

**Issue by yuxingpeng** [kogalur/randomForestSRC#61]
Dear developer, we're facing the memory issue of running this software on a big data-set. The memory usage goes high quickly and then crashed. Is there a way we can estimate the memory need from the size of the data-set and parameters used for the method?

Best regards,

**Comment by kogalur** [comment]
Yes, there is. What is n, and p, the dimensions of your data.  What family of analysis are you running, and what is the function call and parameters you are using?
