### ISSUE TITLE
Fatal Error: Empty Left or Right Daughter Node

### ISSUE THREAD

**Issue by Melton-Elizabeth** [kogalur/randomForestSRC#62]
Hello,

While running imbalanced.rfsrc I have been running into a fatal error that states that a Left of Right Daughter node is empty.  The session must be aborted.  

I have attached a .zip file with a minimal data set and code for reproducing the error.  My information from sessionInfo() is attached at the bottom of the R code.  

Please let me know if you need any other information from me.

Thank you

[Empty_Daughter_Node_Reproduceable.zip](https://github.com/kogalur/randomForestSRC/files/4105309/Empty_Daughter_Node_Reproduceable.zip)

**Comment by kogalur** [comment]
We believe we've tracked this issue down to the fact that there are -Inf values in  column 18 of "ARres_PLB".  A value of NA in data is handled coherently by the package, but +/-Inf was not considered during the design.  Thus, we are analyzing how +/-Inf values are being handled and should be handled.  We'll keep you updated, though we don't expect a rapid turn around on this issue.  We expect a couple of weeks or more, at least.
