### ISSUE TITLE
Clarification on survival analysis

### ISSUE THREAD

**Issue by kingcrimsontianyu** [kogalur/randomForestSRC#64]
Dear developers,

I have a question regarding the survival analysis of this package. The survival forest object has members `survival`, `chf`, `predicted` that are "in-bag" according to the manual, but the way the variable is named seems to suggest that they are defined in accord with equation (3.3) of your paper Ishwaran et al (2008).

So for a sample i with feature Xi, for instance, does `chf` refer to
(1) H = sum of H(t|Xi) where Xi is the in-bag sample / number of trees where Xi is the in-bag sample
or
(2) H = sum of H(t|Xi) regardless of in-bag or OOB / number of trees in total

Thanks for your clarification.

**Comment by kogalur** [comment]
The index i always refers to the case (the row) in the user specified data set.  So, for example, $survival.oob and $survival will both be matrices with n nows (where n is the number of cases in the data set). Thus, $survival.oob[i, ] will be the ensemble for case i.  But only those trees in which i is OOB will contribute to this ensemble. In contrast, $survival[i, ] will be the ensemble for case i, but it will be based on those trees in which i is in-bag.

**Comment by kogalur** [comment]
A small correction on this thread:  $survival[i, ] is composed of all cases regardless of whether i is in-bag or OOB. So it's a mixed ensemble and i gets a contribution from every tree.
