### ISSUE TITLE
randomForestSRC memory issues?

### ISSUE THREAD

**Issue by abadereddeen** [kogalur/randomForestSRC#65]
Dear Developer,
We are trying to use random survival forests to build a predictive model in the presence of competing risk. Our data set has 270,000 observations and 28 variables.
The code ran on a subset of 100,000 observations, but when trying to run on the full data set, it stopped and gave this "
RF-SRC:  *** WARNING *** 
RF-SRC:  S.E.X.P. vector element length exceeds 32-bits:            5364196732
RF-SRC:  S.E.X.P. ALLOC:  oobEnsbCHF 
RF-SRC:  Please Reduce Dimensionality If Possible.
RF-SRC:  *** WARNING *** 
RF-SRC:  S.E.X.P. vector element length exceeds 32-bits:            5364196732
RF-SRC:  S.E.X.P. ALLOC:  oobEnsbCIF 
RF-SRC:  Please Reduce Dimensionality If Possible.
RF-SRC:  *** WARNING *** 
RF-SRC:  S.E.X.P. vector element length exceeds 32-bits:            5364196732
RF-SRC:  S.E.X.P. ALLOC:  allEnsbCHF 
RF-SRC:  Please Reduce Dimensionality If Possible."
any suggestion?

**Comment by kogalur** [comment]
The CHF is an array of dimension [n] x [time interest] x [event type].  Let's assume only one event type.  Thus, the last dimension will be [1].  Assuming every observation has an event, your time interest vector will be of length [n]. So, you are looking at an array of dimension [n] x [n].  This array is flattened and returned as a vector from C to R.  This is well above 2^32 in length.  We don't currently support long vectors in C.  

You need to reduce dimensionality along the time axis.  Set ntime according to the documentation. You can even target segments of the time with successive restorations of the model to recover the full curve. Setting ntime does not effect the model.  It only effects output.

**Comment by abadereddeen** [comment]
Thank you for the quick response, However, I am not sure how to use "ntime" in my code 

"object<-(Surv(time,event)~.,data=input,nsplit=10,ntree=1000,splitrule="logrankCR,cause=(1,1))"

would you please give an example? How to decide the integer to use?
And, if I am interested in VIMP, will this be affected by constraining time?

Thanks again

**Comment by abadereddeen** [comment]
sorry for sending this again:
Thank you for the quick response, However, I am not sure how to use "ntime" in my code

"object<-(Surv(time,event)~.,data=input,nsplit=10,ntree=1000,splitrule="logrankCR,cause=(1,1))"

would you please give an example? How to decide the integer to use?
And, if I am interested in VIMP, will this be affected by constraining time?

Thanks again

**Comment by kogalur** [comment]
All of this is given in detail in the help files.  Please consult them.  VIMP is unaffected by ntime.  The model is unaffected by ntime.  All ntime does is reduce the grid of time values over which the curve is returned.
