### ISSUE TITLE
An issue about the C-index estimation in survival analysis

### ISSUE THREAD

**Issue by zhangfengyi90** [kogalur/randomForestSRC#7]
library(randomForestSRC)
library(ggplot2)
library(Hmisc)
set.seed(1)
Model <- rfsrc(Surv(time, status) ~ ., data = veteran, ntree = 100, tree.err=TRUE,seed=1) 
print(1-Model$err.rate[100])
print(rcorr.cens(predict(Model)$predicted,Surv(veteran$time, veteran$status))[1])

According to your document, the C-index given in the model and the C-index estimated by Harrell's  should be the equal. However, they are quite different. Hence, please provide more information about it. Thanks!

**Comment by kogalur** [comment]
If you compare Model$err.rate and 
rcorr.cens(Model$predicted.oob, Surv(veteran$time, veteran$status)))
you will see that they are nearly identical.  There may be some slight differences due to the way we handle ties.
