### ISSUE TITLE
Question about multiple survival outcomes

### ISSUE THREAD

**Issue by rebeccasartobasso** [kogalur/randomForestSRC#71]
Hi there,

I'm trying to predict multiple correlated outcomes that are a mix of censored, categorical and continuous variables. Is your package able to handle multiple survival outcomes or a mix of survival and other types of outcomes?
I can't find anything in the documentation about this and when I tried to insert a survival object in the multivariate setting it seems to be read as two regression tasks (time and status).
I also looked into Custom Splitting but it seems that I can only add Custom Split rules for regression and classification for a multivariate problem. Is that correct?
If this is the case, is there a reason why you decided to not incorporate multivariate survival? 

Thanks!

Rebecca

**Comment by kogalur** [comment]
There is a custom split rule harness for survival.  But it is only triggered by the survival formula, and will only present you with time and status in the split rule.  There is no way to introduce additional values in the `double **feature` slot of the custom split rule at this point.  The additional issue is that, in a multivariate scenario, we treat each outcome independently of one another, run split-statistics on each outcome and then split based on the average.  But this does not properly account for correlation in the outcomes. We currently don't have theory to point us in directions that are methodologically correct.

If you are experimenting, there might be way for you to proceed.  I would try to treat the data as a multivariate family, and use that custom split rule to define a split statistic.  However, weight all the y-vars but one as zero.  It probably doesn't matter which y-var gets the non-zero weight.  This will allow you to see the non-zero weighted y-var in the `double *response` slot, and the other zero-weighted y-vars in the `double **feature` slot.  You can then design your own split rule as you are presented with all the y-vars in a node.  

You would also set `membership=TRUE` on the R-side, and use $inbag and $membership to define a terminal node statistic for each terminal node, in each tree based on the $inbag data.  You can then even calculate oob ensembles based on your terminal node statistics.  

It's a bit of careful work, or the C-side as well as the R-side, but it might allow you to proceed with your experiment.
