### ISSUE TITLE
Error: NULL distribution encountered during imputation in type

### ISSUE THREAD

**Issue by likeshumidity** [kogalur/randomForestSRC#72]
Using R version 4.0.1.

Getting the error:
```
RF-SRC:  *** ERROR ***
RF-SRC:  NULL distribution encountered during imputation in type: 1
RF-SRC:  Please Contact Technical Support.
```

When running:
```
predictions <- riskRegression:::predictRisk.rfsrc(model,
newdata=data_subset,
times=seq(0, 365, by = 5)
na.action = "na.impute")
```

Was working in R 3.x. Not sure how to troubleshoot. Any recommendations?

**Comment by kogalur** [comment]
I think we'd need a minimal reproducible example, that preferably only uses our package in the call, in order to debug this.
