### ISSUE TITLE
Random forest for Cox Model.

### ISSUE THREAD

**Issue by Dr-Titus100** [kogalur/randomForestSRC#73]
I am conducting a study on survival analysis using the Cox model but now I want to use random forest on my data and I do not know how to do so. I came across this package called "randomForestSRC" but I do not know how to use it. Can anybody offer me some help?

**Comment by ishwaran** [comment]
Appreciate your question, however this forum is meant for software issues and reporting of bugs and not tutorials and guidance on methodology.
