### ISSUE TITLE
seed option working?

### ISSUE THREAD

**Issue by mes86** [kogalur/randomForestSRC#74]
Hi,
I'm want to be able to rerun the same models with each rfsrc run, but even though I enter seed=1978 as an option in the rfsrc code (see example code below), I get different variable importance output on each run. 

Any thoughts would be appreciated. Thanks!
Megan

Code is:
rf <- rfsrc(as.factor(OUTCOME_PSYCHOTHERAPY_ADEQ) ~ . ,                
                        data=data, splitrule="random", ntree=500, importance=TRUE,
                        nsplit=10, nodesize=2, mtry=21, tree.err=TRUE, seed=1978)

**Comment by kogalur** [comment]
See Issue #67 seed does not make variable importance repeatable.
