### ISSUE TITLE
Tune competing risks forest using integrated Brier score

### ISSUE THREAD

**Issue by ledohod** [kogalur/randomForestSRC#75]
Hi,

I don't see an option to change the performance metric while tuning the forest. Is it possible to tune the forest using integrated Brier score instead of the C-index?

Thnaks

**Comment by ishwaran** [comment]
Unfortunately that feature is not currently implemented.  In theory it could be done.

**Comment by ledohod** [comment]
Isn't using integrated Brier score better for survival models? As it takes into account both discrimination and calibration?
