### ISSUE TITLE
Custom regression split functions performance

### ISSUE THREAD

**Issue by MNLR** [kogalur/randomForestSRC#76]
Hi,

I suspect there might be a bug in the package when employing custom split functions. randomForestSRC is giving very poor results when doing regression using the negative log likelihood of the gamma distribution and Mean Absolute Error (MAE) as custom split functions.

I have tried several datasets and the random forest does not seem to adapt to the predictive capacities of the data. When employing the default mse results are reasonable, but something weird is happening when employing custom functions, as MAE should give similar results to mse. 

These are the predictions vs observed values for the mse (I have tried several configurations for the models, this is just an example):

![mse](https://user-images.githubusercontent.com/25566951/92945253-4f6a8580-f455-11ea-8551-f8e6052f97de.png)

Same figure for MAE, using the same configuration:
![mae](https://user-images.githubusercontent.com/25566951/92945261-52fe0c80-f455-11ea-9602-6aec21632705.png)

I attach the code used for both split functions, in case I am missing something.

Thanks a lot,

Mikel.

[custom_split.txt](https://github.com/kogalur/randomForestSRC/files/5209965/custom_split.txt)

**Comment by kogalur** [comment]
Maybe you are using abs() instead of fabs() ?

**Comment by MNLR** [comment]
That was a typo, yep. Still the problem persists with `fabs()`.

**Comment by kogalur** [comment]
Have you tried putting in checks and aborts for illegal arguments in the log() function, the pow() function, divide by zero, or maybe the tgamma() function?

**Comment by MNLR** [comment]
Yes, I have tried printing relevant variables and the delta value is well computed. I think this might have to do with how the algorithm is storing the leaf values...

**Comment by kogalur** [comment]
We're not seeing this issue.  We tried mtcars.  Here are the plots.
![Screen Shot 2021-01-22 at 3 35 40 PM](https://user-images.githubusercontent.com/6853644/105543946-66a16580-5cc8-11eb-9848-1a8e678630fd.png)
![Screen Shot 2021-01-22 at 3 38 22 PM](https://user-images.githubusercontent.com/6853644/105543947-6739fc00-5cc8-11eb-87de-bb76baf05f86.png)
![Screen Shot 2021-01-22 at 3 39 15 PM](https://user-images.githubusercontent.com/6853644/105543949-6739fc00-5cc8-11eb-8481-d581596dd761.png)
