### ISSUE TITLE
Cannot reproduce variable importance with same seed

### ISSUE THREAD

**Issue by yx637718** [kogalur/randomForestSRC#79]
Hi there,

It is weird that I cannot reproduce same var importance for the same code, e.g.:

```
library(randomForestSRC)
data(veteran, package = "randomForestSRC")
v.obj <- rfsrc(Surv(time, status) ~ ., data = veteran, 
               ntree = 100, nodesize = 15, importance="permute", bootstrap="by.root", samptype="swr", seed = -1)
v.obj$importance
```
Two same run result in different results:
![image](https://user-images.githubusercontent.com/71108185/96969017-6916e680-1544-11eb-823d-c26af38a2724.png)

It works well if nodesize/block.size is not specified though. Any clue for this?

Thanks in advance,
XY

**Comment by cttnguyen** [comment]
I think this is the same as #67.
