### ISSUE TITLE
question on recommended `var.select.rfsrc` usage

### ISSUE THREAD

**Issue by MiqG** [kogalur/randomForestSRC#80]
Hi,

I would like to apply the "vh" method `var.select` to identify important genes (*p*>*n*) for survival like in:
- [Iswharan *et al*. 2010](https://www.researchgate.net/publication/227369280_High-Dimensional_Variable_Selection_for_Survival_Data)
- [Zhang *et al*. 2019](https://www.nature.com/articles/s41388-019-0910-7)

In both cases, they performed variable hunting only once even though -I think- the underlying randomness of the forest might affect the importance of the variables every run.
Then, would running the variable selection algorithm several times and combine its results be an overkill?
Of course, every iteration will take quite some time...

After some quick testing, I see that there is, more or less a 50% overlap between the variables selected by the algorithm. I used these parameters:
```{r}
rf = rfsrc(Surv(time,event)~.,data, ntree=1000, nodesize=3)
sel_vars = var.select(rf, method='vh', nrep=100, refit=FALSE, fast=FALSE, conservative='medium')
```

Thanks in advance!

**Comment by ishwaran** [comment]
Keep in mind this is a data mining tool.  Therefore you should be creative in how you use it and keep in mind that it is just a data mining and there are no hard and fast rules per se.
