### ISSUE TITLE
Question about usage of argument samp for block designs problems

### ISSUE THREAD

**Issue by gse-cc-git** [kogalur/randomForestSRC#83]
Hello,

Could you please tell me if I understand correctly what can be done using argument `samp` in the function `rfsrc` ?

Provided that the `bootstrap` argument is set to `by.user`, would one be able to control which samples will be out-of-bag and those that will be inbag for each tree in a forest ?

If this is the case then I think it would be possible to specify groups of samples according to their dependence structure (eg time, space...): do you confirm ?
In this case, for each tree the samples will be either inbag (and possibly >=1 times), not taken in the process (ie not randomly sampled), out-of-bag (and sharing no dependence according to the block id used to create the array of dim `n x ntree`)

I am not sure that inbag samples will not be present out-of-bag in the current implementation.

In fact, my question is [very similar to what was asked for the `inbag` parameter  in `R::ranger` implementation of random forests to allows user to do any kind of block bootstrapping inside a random forest (see here for a much more detailed review of the possibilities)](https://github.com/imbs-hl/ranger/issues/142)

Thank you very much for your time.

**Comment by kogalur** [comment]
bootstrap = by.user requires samp, a matrix of dimension n x ntree specifying exactly how many times each individual appears inbag in the bootstrap for each tree. Thus, individuals having a count of zero are, by definition, out of bag. Ensure that the total inbag count for each tree is the same.
