### ISSUE TITLE
Margins plot question

### ISSUE THREAD

**Issue by giacfalk** [kogalur/randomForestSRC#84]
I am using the `plot.variable.rfsrc` function to produce a marginal effects plot after a `rfsrc `training. 

I interpret it as "the predicted value of the Y variable at different levels of each X, net of the effect of all other control variables".

But is there a function option / formula to evaluate the "predicted n-unit change in the Y in response to a 1 unit change in the X at different levels of X"?

Thanks.

**Comment by giacfalk** [comment]
On a note, I think I could calculate it myself but the core issue is that the yhat and xvar arrays within the object generated via `plot.variable.rfsrc` seem not to be the points being plotted in the output plot. In, fact, if I try to plot them manually via `plot(x, y, type="l")`, the output is very different). Or am I missing something?

**Comment by ishwaran** [comment]
It seems like what you want is more control over the x features that are being used for calculating the partial plot value.  Therefore, we recommend you look at the function "partial.rfsrc" and the help file for illustrative examples.
