### ISSUE TITLE
Why are predictions under rfsrc much slower than under rfsrc.fas?

### ISSUE THREAD

**Issue by chuymtz** [kogalur/randomForestSRC#85]
My question is mostly about how different are models built under rfsrc vs rfsrc.fast. The first thing i noticed was that the predict call takes much longer for fits using rfsrc than rfsrc.fast. I felt that the trees should be the same if my params are the same. Another thing is that as it turns out I'm having a hard time creating the same tree and hence individual "predictions" are very different. 

So in the end, I'm not sure how to evalutate the two implementations. 

Thanks!

**Comment by ishwaran** [comment]
The difference between the two approaches is in the method of sampling used.  For rfsrc.fast we don't use .632 sampling without replacement (which is the default for rfsrc) but instead use a much smaller subsampling size.  This leads to trees that can be grown rapidly as they are constructed from much smaller data sets.  So rfsrc.fast is faster for growing training data.

On the other hand, prediction is based on out-of-bag (out-of-sample data). The out-of-sample size is *larger* for rfsrc.fast.  Therefore it will be slower for prediction.  We have noticed this ourselves on very large data sets and are working on a solution to resolve this theoretical problem.

For reproducibility you should be setting the seed.  Please see help file.
