### ISSUE TITLE
plot vimp max_vars

### ISSUE THREAD

**Issue by asheetal** [kogalur/randomForestSRC#86]
I want to plot vimp. I have a high dimensional dataset. Is there a way to limit max_vars? Something like. 
`
plot(vip, m.target = "B", max_vars =10)
`

**Comment by ishwaran** [comment]
It appears you are talking about plot.variable.  If so, please read the help file in order to correctly set and use options.  In particular, the option you are asking about is called "nvar".

nvar: Number of variables to be plotted. Default is all.
