### ISSUE TITLE
Segfault when data contains `Inf` values

### ISSUE THREAD

**Issue by mcooper** [kogalur/randomForestSRC#87]
Thanks for this great package.

I recently had some issues with `tune.rfsrc()` and `rfsrc()` causing a segfault.  After some digging, it turned out my data had a few `Inf` values, and getting rid of them fixed things.  So, mostly my fault, but I it would be nice for these functions to throw an error in those cases.

**Comment by kogalur** [comment]
We will screen for +/- Inf and gracefully exit with a message in the upcoming build scheduled to be released in a few days.  Thanks.
