### ISSUE TITLE
Missing Prediction-Function for Quantreg

### ISSUE THREAD

**Issue by krennpa** [kogalur/randomForestSRC#88]
Hello! 

Recently, I was using this great package. However, I fear I found an inconvenience in your **prediction-function**!
It proved impossible for me to get predictions for new data under previously fitted **(rfsrc.)quantreg models** for certain quantiles.

I added a small example that will clarify the problem!

Thank you, for having a look at this issue!

````
library(randomForestSRC)
library(mlbench)

data(BostonHousing)
train <- sample(1:nrow(BostonHousing), round(nrow(BostonHousing) * 0.80))

o <- quantreg(medv ~ ., BostonHousing[train,], nodesize = 1, prob=c(0.5,0.7))

# Predictions under the Quantile-model for q=0.5 and q=0.7 (In training Set = fitted values)
o$quantreg$quantiles

# Predictions under the Quantile-model for q=0.5 and q=0.7 (For Testset = missing)
a <- predict(o, BostonHousing[-train,], prob=c(0.5,0.7))

a$quantile

```

**Comment by ishwaran** [comment]
Please see the help file for an example of how to properly implement train/test for quantile regression.

In your example, you should be using:

a <- quantreg(object = o, newdata = BostonHousing[-train,], prob=c(0.5,0.7))
a$quantreg$quantiles

On 1/20/21 3:24 PM, krennpa wrote:
> |library(mlbench) data(BostonHousing) train <- sample(1:nrow(BostonHousing), 
> round(nrow(BostonHousing) * 0.80)) o <- quantreg(medv ~ ., BostonHousing[train,], nodesize = 1, 
> prob=c(0.5,0.7)) # Predictions under the Quantile-model for q=0.5 and q=0.7 (In training Set = 
> fitted values) o$quantreg$quantiles # Predictions under the Quantile-model for q=0.5 and q=0.7 
> (For Testset = missing) a <- predict(o, BostonHousing[-train,], prob=c(0.5,0.7)) a$quantile|


-- 
Hemant Ishwaran
Deputy Statistical Editor, J. Thor. Cardio. Surg.
Director of Statistical Methodology
Professor, Division of Biostatistics
Director of Graduate Studies
Don Soffer Clinical Research Center, Room 1058
1120 NW 14th Street
University of Miami, Miami FL 33136

hemant.ishwaran@gmail.com (preferred)
hishwaran@med.miami.edu
(305) 243-5473 (office)
(305) 243-5544 (fax)

http://web.ccs.miami.edu/~hishwaran

**Comment by krennpa** [comment]
Thank you very very much for your fast and helpful reply! 
It is clear now! I just got confused from the `$quantile` in your predictions object!
