### ISSUE TITLE
Parallel processing lacks efficiency when setting block.size=1 and dataset has over 30 variables

### ISSUE THREAD

**Issue by sinowitabc** [kogalur/randomForestSRC#95]
Hi!  When setting block.size = 1 and dataset has over 30 variables, growing trees using multiple cores takes more time than that of using one core. I installed the package by `install.packages()`. Is this supposed to happen?

Example:
```
library(survival)
library(randomForestSRC)
library(parallel)

set.seed(123)

data("vdv", package = "randomForestSRC")
# default setting
system.time(
  res1 <- rfsrc(Surv(Time, Censoring) ~ ., vdv[rep(seq_len(nrow(vdv)), 10),1:60], block.size = 1, importance = TRUE)
)
# elapsed time 62.613

# 1 core
options(rf.cores = 1)
system.time(
  res2 <- rfsrc(Surv(Time, Censoring) ~ ., vdv[rep(seq_len(nrow(vdv)), 10),1:60], block.size = 1, importance = TRUE)
)
# elapsed time 37.530

# 56 cores (same as default setting)
options(rf.cores = detectCores())
system.time(
  res3 <- rfsrc(Surv(Time, Censoring) ~ ., vdv[rep(seq_len(nrow(vdv)), 10),1:60], block.size = 1, importance = TRUE)
)
# elapsed time 61.965

```
`sessionInfo()`

R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.7 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C               LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8    LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] randomForestSRC_2.10.1 survival_3.2-10       

loaded via a namespace (and not attached):
 [1] lattice_0.20-41    visNetwork_2.0.9   digest_0.6.27      grid_3.6.3         R6_2.5.0           jsonlite_1.7.2    
 [7] magrittr_2.0.1     rlang_0.4.10       stringi_1.5.3      Matrix_1.3-2       DiagrammeR_1.0.6.1 splines_3.6.3     
[13] data.tree_1.0.0    RColorBrewer_1.1-2 tools_3.6.3        glue_1.4.2         htmlwidgets_1.5.3  compiler_3.6.3    
[19] htmltools_0.5.1.1

**Comment by kogalur** [comment]
Well, we think it's possible for this to happen. We do not know what is your population size n, but it appears you have p = 60.  With block.size = 1 and importance = T, you are permuting the OOB subset on every tree and calculating concordance pairs (which is of order OOB(n)^2) for every tree and every x-var (so this would total of order ntree x p x n^2). When a tree is finished growing in a thread, we allow that thread to update performance related ensembles, calculate and update VIMP related ensembles, calculate performance, and calculate VIMP.  Normally, a thread (tree) can accomplish this with minimal locking, but in your scenario, the amount of time needed during the lock is likely quite large in comparison to the time required to grow the tree.  This results in trees stopping and waiting in line to calculate tree-specific VIMP using the associated concordance pair calculations.  It's not clear why serial mode is faster. We don't know what is your installed RAM. There may also be memory bandwidth limitations coming in to play, causing additional wait times and/or paging.  You might want to look at user/system/elapsed times for rf.cores = c(1, 2, 4, 8, 16, 32) if you are curious.  We'd recommend doing a call with the default block.size, and importance=F during the grow phase of your analysis, and then seek importance=T in a separate predict call.

**Comment by sinowitabc** [comment]
Thank you for your reply and advice. You are right that calculating performance and VIMP takes much more time than that of growing trees. So I'm wondering if there is any way to speed it up?

Another example:
```
library(survival)
library(randomForestSRC)
library(parallel)
library(data.table)
set.seed(123)

data("vdv", package = "randomForestSRC")

# Grow trees with default setting
print("Grow trees with default setting")
tmc <- system.time(
  res <- rfsrc(Surv(Time, Censoring) ~ ., vdv[rep(seq_len(nrow(vdv)), 20),1:60])
)
print(tmc)
print(res)

# Restore trees with different settings
print("Restore trees with default setting")
fx <- function(ncore) {
  options(rf.cores = ncore)
  tmc <- system.time(
    pred <- predict(
      res,
      block.size = 1,
      importance = TRUE
      )
  )
  tmc <- as.list(summary(tmc))
}

ncores = c(1, 2, 4, 8, 16, 32)

tmcs <- lapply(ncores, fx)
tmcs <- rbindlist(tmcs)
tmcs$ncore <- ncores
print(tmcs)
```
output:
[1] "Grow trees with default setting"
   user  system elapsed 
 10.396   0.104   0.654 
                         Sample size: 1560
                    Number of deaths: 680
                     Number of trees: 1000
           Forest terminal node size: 15
       Average no. of terminal nodes: 31.039
No. of variables tried at each split: 8
              Total no. of variables: 58
       Resampling used to grow trees: swor
    Resample size used to grow trees: 986
                            Analysis: RSF
                              Family: surv
                      Splitting rule: logrank *random*
       Number of random split points: 10
                          Error rate: 1.11%
[1] "Restore trees with default setting"
      user system elapsed ncore
1: 139.508  0.068 139.577     1
2: 225.656  0.076 223.625     2
3: 222.624  0.088 220.560     4
4: 226.344  0.096 224.252     8
5: 222.952  0.080 220.768    16
6: 218.384  0.148 216.081    32

**Comment by kogalur** [comment]
We're looking into this.  We'll keep you posted.

**Comment by flippercy** [comment]
Thank you. Based on my experience it seems that the process is single-threaded as long as importance = 'permute'; increasing block.size helped a bit but did not change the utilization of CPUs.

**Comment by kogalur** [comment]
Upgrade to Version 2.12.0 to resolve this issue.  Thank you.
