### ISSUE TITLE
Is calculating vimp a single-threaded process?

### ISSUE THREAD

**Issue by flippercy** [kogalur/randomForestSRC#96]
Hi:

I've been using rfsrc to build survival forests; based on my monitoring of the backend, it seemed that the calculation of variable importance was a single-threaded process (only one CPU was active), which made the entire process-quite time consuming.

Is it possible to make it a multi-threaded process? Based on my understanding permutation can be calculated by multiple CPUs in parallel. Or did I code it wrong?

Appreciate your help!

**Comment by kogalur** [comment]
We coded it wrong.  In certain scenarios, such as with block.size = 1, and importance="permute", threads are apparently locking. We're working on a fix. We're closing this, issue,  and referring you to Issue #95, where you can continue the thread.  The work around, which may or may not work, for now is to go with a larger block.size (even ntree), and importance="random".
