### ISSUE TITLE
rfsrc returns weird results for survival forests

### ISSUE THREAD

**Issue by flippercy** [kogalur/randomForestSRC#97]
Hi:

I am using rfsrc for survival analysis on right-censored data and getting some odd results.

From the perspective of rank ordering, the model performs well; its AUC, concordance and KS all beat benchmarks and competitors such as coxph easily; however, we'd like to use this model to predict the # of events in each time window and that's where I start to have some issues.

Due to the nature of our data, there is barely any event in the first couple of time windows; however, the model fitted by rfsrc failed to capture this pattern. When I used the final model to predict new datasets, the results always forecast considerable amount of events in the first couple of time windows (using $survival in the prediction for calculation). As a result, the model is not usable although having great concordance and AUC. On the other hand, the cox model, with a less concordance and AUC, captured this pattern and correctly predicted that there would be only a few events in the early period.

I've checked my modeling process back and forth but could not figure out the reason for this discrepancy. Any idea or advice?

Appreciate your help!

**Comment by ledohod** [comment]
I think you might need to calibrate your model. The hyper-parameter optimisation is done based on C-statistic, which focuses only on discrimination and not calibration. Although, the paper describes the integrated brier score (IBS), which covers both discrimination and calibration, it doesn't seem that IBS has actually been implemented. Calibration is very important, so I wish IBS was an option for both hyper-parameter optimisation and for variable importance.

I think you need to re-calibrate your model, maybe using something like isotonic regression or more recent beta calibration.

**Comment by flippercy** [comment]
Make sense @ledohod. Waiting for the response from the authors.

**Comment by ishwaran** [comment]
There are a lot of issues at play here.  For one thing, predicting the number of events is a topic in itself.  Not sure that survival would be the correct way to do this: for example the cumulative hazard function may be a better way to approach that issue. What we really need is a simple reproducible example that illustrates the issue.  Otherwise there are just too many things at play to be able to diagnose the problem.

**Comment by flippercy** [comment]
Hi Dr. Ishwaran:

Thank you for the quick response! 

I've double checked the predictions made by the survival model built with rfsrc; it turns out that for each record, the predicted survival probability during the first a few time windows is closed to 1 (0.999 ish), reflecting the pattern of the modeling data (barely any event happened in the first a fewtime windows); however, due to the big size of my test data (hundreds of thousands of records), when calculating the # of events as N (total # of records) - sum(survival probability), the result I got is significantly different from the actual, which is nearly zero.

As you mentioned, probably the model itself worked as expected but the problem, which is to predict the # of events per time window, should be tackled using other methods. Do you have any suggestions, please?

Appreciate your help!


I
