### ISSUE TITLE
get.tree(...class.type())  

### ISSUE THREAD

**Issue by Jiangnan-Lyu** [kogalur/randomForestSRC#98]
According to the helper file: 
**2. For classification, it is the predicted class probability specified by ‘target’, or the class of
maximum probability depending on whether ‘class.type’ is set to "prob" or "bayes".**

I ran some trials but I'm very confused how the number marked at each terminal nodes are calculated. What probability estimation algorithm is used for deriving the "prob" values? I expected to see 0 1 0 1 when class.type is changed from default "prob" to "bayes",  however, the second node is 0 instead of 1 (**the data I use is binary, dim[X]=40 by 4, balanced-class**）:
![2](https://user-images.githubusercontent.com/65414652/117312976-7c8bfe00-ae53-11eb-9101-0c440313f372.PNG)
![1](https://user-images.githubusercontent.com/65414652/117312978-7c8bfe00-ae53-11eb-8679-68c38c4edfc1.PNG)

I initially thought the numbers **n** marked at each terminal node is based on the bootstrapped samples used for creating that tree, but when I traced the detail of tree rules, it seems to me that the original training data is used instead of bootstrapped samples, because each of the 40 samples appear exactly once for each tree (I set ntree=2 for this example. Again the training data I use is 40 by 4, response variable=c(rep(0,20),rep(1,20)) ordered):

![6](https://user-images.githubusercontent.com/65414652/117324363-b8c45c00-ae5d-11eb-95c3-4cfb1323ec6c.PNG)
![7](https://user-images.githubusercontent.com/65414652/117324364-b95cf280-ae5d-11eb-8572-9fbf69732b06.PNG)
![5](https://user-images.githubusercontent.com/65414652/117324365-b95cf280-ae5d-11eb-88e3-43d8bf9c72ee.PNG)

Also, how the predicted posterior probability **f(xi|y=0)** when I call **"o$predicted[,1]**" is calculated?

**Comment by ishwaran** [comment]
Thank you for your questions.

1. class.type = "prob", "bayes" selects between maximal probability and bayes classification. In your case, the bayes classifier will either be 0/1.  The probability values are calculated by averaging tree predicted probabilities (either in bag or out-of-bag, the latter is the default). The tree predicted probability is the relative frequency of the class labels within a given terminal node (again, either inbag or out-of-bag).
2. As stated in the help file, predicted value equals the forest ensemble value and not the tree predicted value.  This is done as it allows one to visualize the ensemble predictor over a given tree and therefore a given partition of the feature space.
3. Same comment applies to n although the help file could be improved to be more clear on this.

**Comment by Jiangnan-Lyu** [comment]
Thank you so much for the explaination!

**Comment by ishwaran** [comment]
In the next build we will make it possible for the user to select between predicted values for the tree (where sample size is for the cases in the tree) or the ensemble (where sample size is for the cases in the entire data).  By default, we will show the predicted values for the tree.  

Thank you for comments which suggested this nice improvement to the function.
